unpackaged/main/default/objects/General_Preferences__c/General_Preferences__c.object-meta.xml
<CustomObject>
    <label>General Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferences/Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/General_Preferences__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>General Preferences</relationshipLabel>
    <relationshipName>Client_PreferencesContact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/Linked_General_Preference__c.object-meta.xml
<CustomObject>
    <label>Linked General Preference</label>
    <nameField>
        <displayFormat>LGP-{0}</displayFormat>
        <label>Linked General Preference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_Between__c.field-meta.xml
<CustomField>
    <fullName>Linked_Between__c</fullName>
    <formula>HYPERLINK('/' + Linked_General_Preference_From__r.Contact_Name__c, Linked_General_Preference_From__r.Contact_Name__r.Full_Name__c) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_General_Preference_To__r.Contact_Name__c, Linked_General_Preference_To__r.Contact_Name__r.Full_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Between</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference__c</fullName>
    <formula>HYPERLINK('/' + Linked_General_Preference_From__c, Linked_General_Preference_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_General_Preference_To__c, Linked_General_Preference_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked General Preference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_From__c</fullName>
    <label>Linked General Preference From</label>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (From)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This general preference will initially be synced to the general preference selected here. Then they will be synced up whenever either general preference is updated.</inlineHelpText>
    <label>Linked General Preference To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_General_Preference_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (To)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LinkedGeneralPreferenceController.cls
public class LinkedGeneralPreferenceController {
    @AuraEnabled
    public static List <LinkedGeneralPreferenceWrapper> getLinkedGeneralPreferences(Id generalPreferenceId) {
        system.debug('LinkedGeneralPreferenceController');
        List <LinkedGeneralPreferenceWrapper> linkedGeneralPreferences = new List<LinkedGeneralPreferenceWrapper>();
        
        Set<Id> linkedGeneralPreferenceIds = new Set<Id>();
        Set<Id> generalPreferenceIds = new Set<Id>();
        Set<Id> alreadyLinkedIds = new Set<Id>();
        
        for (Linked_General_Preference__c lgp : [SELECT Id,Name,Linked_Between__c,Linked_General_Preference_To__c,Linked_General_Preference_From__c,Linked_General_Preference_From__r.Id,Linked_General_Preference_From__r.Name,Linked_General_Preference_From__r.Contact_Name__c,Linked_General_Preference_From__r.Contact_Name__r.Full_Name__c,
                                                 Linked_General_Preference_To__r.Id,Linked_General_Preference_To__r.Name,Linked_General_Preference_To__r.Contact_Name__c,Linked_General_Preference_To__r.Contact_Name__r.Full_Name__c
                                                 FROM Linked_General_Preference__c
                                                 WHERE Linked_General_Preference_From__c = :generalPreferenceId OR Linked_General_Preference_To__c = :generalPreferenceId]) {
                                                     linkedGeneralPreferenceIds.add(lgp.Id);
                                                     if (lgp.Linked_General_Preference_From__c != generalPreferenceId) {
                                                         linkedGeneralPreferences.add(new LinkedGeneralPreferenceWrapper(lgp, lgp.Linked_General_Preference_From__r.Name, lgp.Linked_General_Preference_From__r.Id,lgp.Linked_General_Preference_From__r.Contact_Name__c,lgp.Linked_General_Preference_From__r.Contact_Name__r.Full_Name__c, '1 - DIRECT'));
                                                         alreadyLinkedIds.add(lgp.Linked_General_Preference_From__r.Id);
                                                     } else {
                                                         linkedGeneralPreferences.add(new LinkedGeneralPreferenceWrapper(lgp, lgp.Linked_General_Preference_To__r.Name, lgp.Linked_General_Preference_To__r.Id,lgp.Linked_General_Preference_To__r.Contact_Name__c,lgp.Linked_General_Preference_To__r.Contact_Name__r.Full_Name__c,'1 - DIRECT'));
                                                         alreadyLinkedIds.add(lgp.Linked_General_Preference_To__r.Id);
                                                     }
                                                     generalPreferenceIds.add(lgp.Linked_General_Preference_From__r.Id);
                                                     generalPreferenceIds.add(lgp.Linked_General_Preference_To__r.Id);
                                                 }
        
        //loop 5 times to get general preferences 9 levels deep...
        Integer listSize = generalPreferenceIds.size();
        for (Integer i = 2; i < 11; i++) {
            System.debug('i: ' + i);
            
            for (Linked_General_Preference__c lgp : [SELECT Id,Name,Linked_Between__c,Linked_General_Preference_To__c,Linked_General_Preference_From__c,Linked_General_Preference_From__r.Id,Linked_General_Preference_From__r.Name,Linked_General_Preference_From__r.Contact_Name__c,Linked_General_Preference_From__r.Contact_Name__r.Full_Name__c,
                                                     Linked_General_Preference_To__r.Id,Linked_General_Preference_To__r.Name,Linked_General_Preference_To__r.Contact_Name__c,Linked_General_Preference_To__r.Contact_Name__r.Full_Name__c
                                                     FROM Linked_General_Preference__c
                                                     WHERE (Linked_General_Preference_From__c IN :generalPreferenceIds OR Linked_General_Preference_To__c IN :generalPreferenceIds) AND Id NOT IN :linkedGeneralPreferenceIds]) {
                                                         if (!alreadyLinkedIds.contains(lgp.Linked_General_Preference_From__r.Id)) {
                                                             linkedGeneralPreferences.add(new LinkedGeneralPreferenceWrapper(lgp, lgp.Linked_General_Preference_From__r.Name, lgp.Linked_General_Preference_From__r.Id,lgp.Linked_General_Preference_From__r.Contact_Name__c,lgp.Linked_General_Preference_From__r.Contact_Name__r.Full_Name__c,String.valueOf(i) + ' - NON-DIRECT'));
                                                         }
                                                         if (!alreadyLinkedIds.contains(lgp.Linked_General_Preference_To__r.Id)) {
                                                             linkedGeneralPreferences.add(new LinkedGeneralPreferenceWrapper(lgp, lgp.Linked_General_Preference_To__r.Name, lgp.Linked_General_Preference_To__r.Id,lgp.Linked_General_Preference_To__r.Contact_Name__c,lgp.Linked_General_Preference_To__r.Contact_Name__r.Full_Name__c,String.valueOf(i) + ' - NON-DIRECT'));
                                                         }
                                                         alreadyLinkedIds.add(lgp.Linked_General_Preference_From__r.Id);
                                                         alreadyLinkedIds.add(lgp.Linked_General_Preference_To__r.Id);
                                                         generalPreferenceIds.add(lgp.Linked_General_Preference_From__r.Id);
                                                         generalPreferenceIds.add(lgp.Linked_General_Preference_To__r.Id);
                                                     }
            
            //if list didn't increase, means no more linked to find so exit
            if (listSize == generalPreferenceIds.size()) {
                break;
            } else {
                listSize = generalPreferenceIds.size();
            }
        }
        return linkedGeneralPreferences;
    }
    
    public class LinkedGeneralPreferenceWrapper {
        @AuraEnabled
        public Linked_General_Preference__c rec {get; set;}
        @AuraEnabled
        public String generalPreference {get; set;}
        @AuraEnabled
        public Id generalPreferenceId {get; set;}
        @AuraEnabled
        public Id contactId {get; set;}
        @AuraEnabled
        public String contactName {get; set;}
        @AuraEnabled
        public String syncLevel {get;set;}
        @AuraEnabled
        public Integer linkBetween {get;set;}
        
        public LinkedGeneralPreferenceWrapper(Linked_General_Preference__c rec, String generalPreference, Id generalPreferenceId, Id contactId, String contactName, String syncLevel) {     
            this.rec = rec;
            this.generalPreference = generalPreference;
            this.generalPreferenceId = generalPreferenceId;
            this.contactId = contactId;
            this.contactName = contactName;
            this.syncLevel = syncLevel;
        }
    }
}