unpackaged/main/default/objects/General_Preferences__c/General_Preferences__c.object-meta.xml
<CustomObject>
    <label>General Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferences/Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/General_Preferences__c/fields/Airline_Seat_Preference__c.field-meta.xml
<CustomField>
    <fullName>Airline_Seat_Preference__c</fullName>
    <label>Airline Seat Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Aisle</fullName>
            </value>
            <value>
                <fullName>Window</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Car_Rental_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Preferences__c</fullName>
    <label>Car Rental Preferences - DNU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alamo</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Dollar</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Hertz</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Sixt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Gym__c.field-meta.xml
<CustomField>
    <fullName>Gym__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gym</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Member_of_Social_or_Athletic_Club__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Social_or_Athletic_Club__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Member of Social or Athletic Club</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Notes_Summary__c.field-meta.xml
<CustomField>
    <fullName>Notes_Summary__c</fullName>
    <description>This is a summary field for notes. Set via WF rule.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Means_of_Air_Travel__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Means_of_Air_Travel__c</fullName>
    <label>Preferred Means of Air Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Seating_Class__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Seating_Class__c</fullName>
    <label>Preferred Seating Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy Plus</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Account - Restaurant, Vendor Account - Generic</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>General_Preferences9</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Repeat_Orders__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Orders__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Repeat Orders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Room_Preference__c.field-meta.xml
<CustomField>
    <fullName>Room_Preference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Preference</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Season_Ticket_Holder__c.field-meta.xml
<CustomField>
    <fullName>Season_Ticket_Holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Season Ticket Holder</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Security_Q_A__c.field-meta.xml
<CustomField>
    <fullName>Security_Q_A__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Security Q&amp;A</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Sports_Played__c.field-meta.xml
<CustomField>
    <fullName>Sports_Played__c</fullName>
    <label>Sports Played</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Basketball</fullName>
            </value>
            <value>
                <fullName>Biking</fullName>
            </value>
            <value>
                <fullName>Climbing</fullName>
            </value>
            <value>
                <fullName>Figure skating</fullName>
            </value>
            <value>
                <fullName>Football</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Gymnastics</fullName>
            </value>
            <value>
                <fullName>Hiking</fullName>
            </value>
            <value>
                <fullName>Hockey</fullName>
            </value>
            <value>
                <fullName>Horseback Riding</fullName>
            </value>
            <value>
                <fullName>Lacrosse</fullName>
            </value>
            <value>
                <fullName>Martial Arts</fullName>
            </value>
            <value>
                <fullName>Rowing</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Scuba diving</fullName>
            </value>
            <value>
                <fullName>Skiing</fullName>
            </value>
            <value>
                <fullName>Snowboarding</fullName>
            </value>
            <value>
                <fullName>Soccer</fullName>
            </value>
            <value>
                <fullName>Softball</fullName>
            </value>
            <value>
                <fullName>Surfing</fullName>
            </value>
            <value>
                <fullName>Swimming</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Volleyball</fullName>
            </value>
            <value>
                <fullName>Wrestling</fullName>
            </value>
            <value>
                <fullName>Yoga</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Abseiling</fullName>
                <isActive>false</isActive>
                <label>Abseiling</label>
            </value>
            <value>
                <fullName>Aerobics</fullName>
                <isActive>false</isActive>
                <label>Aerobics</label>
            </value>
            <value>
                <fullName>Aikido</fullName>
                <isActive>false</isActive>
                <label>Aikido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Venue for Facials</fullName>
            </value>
            <value>
                <fullName>Venue for Haircuts</fullName>
            </value>
            <value>
                <fullName>Venue for Massages</fullName>
            </value>
            <value>
                <fullName>Dermatologist</fullName>
            </value>
            <value>
                <fullName>Personal Trainer</fullName>
            </value>
            <value>
                <fullName>PT/Acupuncture</fullName>
            </value>
            <value>
                <fullName>Nutritionist</fullName>
            </value>
            <value>
                <fullName>Studio/Class</fullName>
            </value>
            <value>
                <fullName>Favorite Restaurant</fullName>
            </value>
            <value>
                <fullName>Business Dinner</fullName>
            </value>
            <value>
                <fullName>Business Lunch</fullName>
            </value>
            <value>
                <fullName>Business Breakfast</fullName>
            </value>
            <value>
                <fullName>Special Occasion</fullName>
            </value>
            <value>
                <fullName>Weekend Brunch</fullName>
            </value>
            <value>
                <fullName>Cuisine</fullName>
            </value>
            <value>
                <fullName>Quiet Dinner</fullName>
            </value>
            <value>
                <fullName>Restaurant Investor In</fullName>
            </value>
            <value>
                <fullName>Restaurant Client Doesn't Like</fullName>
            </value>
            <value>
                <fullName>Trendy/Fun Scene</fullName>
            </value>
            <value>
                <fullName>Clothing Style</fullName>
            </value>
            <value>
                <fullName>Interests/Hobbies</fullName>
            </value>
            <value>
                <fullName>Cocktail</fullName>
            </value>
            <value>
                <fullName>Wine - RED</fullName>
            </value>
            <value>
                <fullName>Wine - WHITE</fullName>
            </value>
            <value>
                <fullName>Wine - other</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Vacation_Locale_Preference__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Locale_Preference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vacation Locale Preference</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/Linked_General_Preference__c.object-meta.xml
<CustomObject>
    <label>Linked General Preference</label>
    <nameField>
        <displayFormat>LGP-{0}</displayFormat>
        <label>Linked General Preference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference__c</fullName>
    <formula>HYPERLINK('/' + Linked_General_Preference_From__c, Linked_General_Preference_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_General_Preference_To__c, Linked_General_Preference_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked General Preference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_From__c</fullName>
    <label>Linked General Preference From</label>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (From)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This general preference will initially be synced to the general preference selected here. Then they will be synced up whenever either general preference is updated.</inlineHelpText>
    <label>Linked General Preference To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_General_Preference_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (To)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerGeneralPreference.cls
public  class TriggerHandlerGeneralPreference extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerGeneralPreference() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert()  {}
    public override void afterUpdate()  {
        if(RecursiveTriggerHandler.runOnce()){
            syncGeneralPreferences(Trigger.new);
        }
    }
    public override void afterDelete()  {
    }
    public override void afterUndelete(){
    }
    
    private void syncGeneralPreferences(List<sObject> newGeneralPreferences){
        system.debug('syncGeneralPreferences');
        List<General_Preferences__c> newGeneralPreferenceList = (List<General_Preferences__c>) newGeneralPreferences;
        List<General_Preferences__c> generalPreferencesToUpdate = new List<General_Preferences__c>();
                
        for(General_Preferences__c primaryGeneralPreference : newGeneralPreferenceList){
            system.debug('Sync From GeneralPreferences');
            Set<Id> linkedGeneralPreferenceIds = new Set<Id>();
            Set<Id> generalPreferenceIds = new Set<Id>();
            
            for (Linked_General_Preference__c lgp : [SELECT Id, Linked_General_Preference_From__r.Id, Linked_General_Preference_To__r.Id FROM Linked_General_Preference__c WHERE Linked_General_Preference_From__c = :primaryGeneralPreference.Id OR Linked_General_Preference_To__c = :primaryGeneralPreference.Id]) {
                linkedGeneralPreferenceIds.add(lgp.Id);
                generalPreferenceIds.add(lgp.Linked_General_Preference_From__r.Id);
                generalPreferenceIds.add(lgp.Linked_General_Preference_To__r.Id);
            }
            
            //loop to get generalPreferences 9 levels deep...
            Integer listSize = generalPreferenceIds.size();
            for (Integer i = 0; i < 9; i++) {
                System.debug('i: ' + i);
                
                for (Linked_General_Preference__c lgp : [SELECT Id, Linked_General_Preference_From__r.Id, Linked_General_Preference_To__r.Id FROM Linked_General_Preference__c WHERE Linked_General_Preference_From__c IN :generalPreferenceIds OR Linked_General_Preference_To__c IN :generalPreferenceIds]) {
                    linkedGeneralPreferenceIds.add(lgp.Id);
                    generalPreferenceIds.add(lgp.Linked_General_Preference_From__r.Id);
                    generalPreferenceIds.add(lgp.Linked_General_Preference_To__r.Id);
                }
                
                //if list didn't increase, means no more generalPreferences to find so exit
                if (listSize == generalPreferenceIds.size()) {
                    break;
                } else {
                    listSize = generalPreferenceIds.size();
                }
            }
            
            system.debug('primaryGeneralPreference: ' + primaryGeneralPreference);
            
            for (Id childGpId : generalPreferenceIds) {
                if (childGpId == primaryGeneralPreference.Id) {
                    continue;
                } else {
                    General_Preferences__c childGeneralPreference = new General_Preferences__c(Id = childGpId);
                    childGeneralPreference.Account_Number__c = primaryGeneralPreference.Account_Number__c;
                    childGeneralPreference.Airline_Seat_Preference__c = primaryGeneralPreference.Airline_Seat_Preference__c;
                    childGeneralPreference.Avid_Wine_Collector__c = primaryGeneralPreference.Avid_Wine_Collector__c;
                    childGeneralPreference.Car_Rental_Preferences__c = primaryGeneralPreference.Car_Rental_Preferences__c;
                    childGeneralPreference.Gym__c = primaryGeneralPreference.Gym__c;
                    childGeneralPreference.Member_of_Social_or_Athletic_Club__c = primaryGeneralPreference.Member_of_Social_or_Athletic_Club__c;
                    childGeneralPreference.Notes_Summary__c = primaryGeneralPreference.Notes_Summary__c;
                    childGeneralPreference.Notes__c = primaryGeneralPreference.Notes__c;
                    childGeneralPreference.Password__c = primaryGeneralPreference.Password__c;
                    childGeneralPreference.Preferred_Means_of_Air_Travel__c = primaryGeneralPreference.Preferred_Means_of_Air_Travel__c;
                    childGeneralPreference.Preferred_Seating_Class__c = primaryGeneralPreference.Preferred_Seating_Class__c;
                    childGeneralPreference.RecordTypeId = primaryGeneralPreference.RecordTypeId;
                    childGeneralPreference.Repeat_Orders__c = primaryGeneralPreference.Repeat_Orders__c;
                    childGeneralPreference.Room_Preference__c = primaryGeneralPreference.Room_Preference__c;
                    childGeneralPreference.Season_Ticket_Holder__c = primaryGeneralPreference.Season_Ticket_Holder__c;
                    childGeneralPreference.Security_Q_A__c = primaryGeneralPreference.Security_Q_A__c;
                    childGeneralPreference.Sports_Played__c = primaryGeneralPreference.Sports_Played__c;
                    childGeneralPreference.Status__c = primaryGeneralPreference.Status__c;
                    childGeneralPreference.Sub_Type__c = primaryGeneralPreference.Sub_Type__c;
                    childGeneralPreference.Type__c = primaryGeneralPreference.Type__c;
                    childGeneralPreference.Username__c = primaryGeneralPreference.Username__c;
                    childGeneralPreference.Vacation_Locale_Preference__c = primaryGeneralPreference.Vacation_Locale_Preference__c;
                    childGeneralPreference.Preferred_Vendor__c = primaryGeneralPreference.Preferred_Vendor__c;
                    childGeneralPreference.Wine_Cellar__c = primaryGeneralPreference.Wine_Cellar__c;
                    generalPreferencesToUpdate.add(childGeneralPreference); 
                }
            }
        }
        
        if (!generalPreferencesToUpdate.isEmpty()) {
            system.debug('generalPreferencesToUpdate: ' + generalPreferencesToUpdate);
            system.debug('generalPreferencesToUpdate.size(): ' + generalPreferencesToUpdate.size());
            update generalPreferencesToUpdate;
        }
    }
}