unpackaged/main/default/objects/General_Preferences__c/General_Preferences__c.object-meta.xml
<CustomObject>
    <label>General Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferences/Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/General_Preferences__c/fields/Airline_Seat_Preference__c.field-meta.xml
<CustomField>
    <fullName>Airline_Seat_Preference__c</fullName>
    <label>Airline Seat Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Aisle</fullName>
            </value>
            <value>
                <fullName>Window</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Car_Rental_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Preferences__c</fullName>
    <label>Car Rental Preferences - DNU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alamo</fullName>
            </value>
            <value>
                <fullName>Avis</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Dollar</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Hertz</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Sixt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Gym__c.field-meta.xml
<CustomField>
    <fullName>Gym__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gym</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Member_of_Social_or_Athletic_Club__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Social_or_Athletic_Club__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Member of Social or Athletic Club</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Notes_Summary__c.field-meta.xml
<CustomField>
    <fullName>Notes_Summary__c</fullName>
    <description>This is a summary field for notes. Set via WF rule.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Means_of_Air_Travel__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Means_of_Air_Travel__c</fullName>
    <label>Preferred Means of Air Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Seating_Class__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Seating_Class__c</fullName>
    <label>Preferred Seating Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy Plus</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Account - Restaurant, Vendor Account - Generic</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>General_Preferences9</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Repeat_Orders__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Orders__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Repeat Orders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Room_Preference__c.field-meta.xml
<CustomField>
    <fullName>Room_Preference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Preference</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Season_Ticket_Holder__c.field-meta.xml
<CustomField>
    <fullName>Season_Ticket_Holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Season Ticket Holder</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Security_Q_A__c.field-meta.xml
<CustomField>
    <fullName>Security_Q_A__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Security Q&amp;A</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Sports_Played__c.field-meta.xml
<CustomField>
    <fullName>Sports_Played__c</fullName>
    <label>Sports Played</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Basketball</fullName>
            </value>
            <value>
                <fullName>Biking</fullName>
            </value>
            <value>
                <fullName>Climbing</fullName>
            </value>
            <value>
                <fullName>Figure skating</fullName>
            </value>
            <value>
                <fullName>Football</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Gymnastics</fullName>
            </value>
            <value>
                <fullName>Hiking</fullName>
            </value>
            <value>
                <fullName>Hockey</fullName>
            </value>
            <value>
                <fullName>Horseback Riding</fullName>
            </value>
            <value>
                <fullName>Lacrosse</fullName>
            </value>
            <value>
                <fullName>Martial Arts</fullName>
            </value>
            <value>
                <fullName>Rowing</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Scuba diving</fullName>
            </value>
            <value>
                <fullName>Skiing</fullName>
            </value>
            <value>
                <fullName>Snowboarding</fullName>
            </value>
            <value>
                <fullName>Soccer</fullName>
            </value>
            <value>
                <fullName>Softball</fullName>
            </value>
            <value>
                <fullName>Surfing</fullName>
            </value>
            <value>
                <fullName>Swimming</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Volleyball</fullName>
            </value>
            <value>
                <fullName>Wrestling</fullName>
            </value>
            <value>
                <fullName>Yoga</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Abseiling</fullName>
                <isActive>false</isActive>
                <label>Abseiling</label>
            </value>
            <value>
                <fullName>Aerobics</fullName>
                <isActive>false</isActive>
                <label>Aerobics</label>
            </value>
            <value>
                <fullName>Aikido</fullName>
                <isActive>false</isActive>
                <label>Aikido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Venue for Facials</fullName>
            </value>
            <value>
                <fullName>Venue for Haircuts</fullName>
            </value>
            <value>
                <fullName>Venue for Massages</fullName>
            </value>
            <value>
                <fullName>Dermatologist</fullName>
            </value>
            <value>
                <fullName>Personal Trainer</fullName>
            </value>
            <value>
                <fullName>PT/Acupuncture</fullName>
            </value>
            <value>
                <fullName>Nutritionist</fullName>
            </value>
            <value>
                <fullName>Studio/Class</fullName>
            </value>
            <value>
                <fullName>Favorite Restaurant</fullName>
            </value>
            <value>
                <fullName>Business Dinner</fullName>
            </value>
            <value>
                <fullName>Business Lunch</fullName>
            </value>
            <value>
                <fullName>Business Breakfast</fullName>
            </value>
            <value>
                <fullName>Special Occasion</fullName>
            </value>
            <value>
                <fullName>Weekend Brunch</fullName>
            </value>
            <value>
                <fullName>Cuisine</fullName>
            </value>
            <value>
                <fullName>Quiet Dinner</fullName>
            </value>
            <value>
                <fullName>Restaurant Investor In</fullName>
            </value>
            <value>
                <fullName>Restaurant Client Doesn't Like</fullName>
            </value>
            <value>
                <fullName>Trendy/Fun Scene</fullName>
            </value>
            <value>
                <fullName>Clothing Style</fullName>
            </value>
            <value>
                <fullName>Interests/Hobbies</fullName>
            </value>
            <value>
                <fullName>Cocktail</fullName>
            </value>
            <value>
                <fullName>Wine - RED</fullName>
            </value>
            <value>
                <fullName>Wine - WHITE</fullName>
            </value>
            <value>
                <fullName>Wine - other</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Vacation_Locale_Preference__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Locale_Preference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vacation Locale Preference</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Wine_Cellar__c.field-meta.xml
<CustomField>
    <fullName>Wine_Cellar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wine Cellar</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/Linked_General_Preference__c.object-meta.xml
<CustomObject>
    <label>Linked General Preference</label>
    <nameField>
        <displayFormat>LGP-{0}</displayFormat>
        <label>Linked General Preference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Link_General_Preference_To__c.field-meta.xml
<CustomField>
    <fullName>Link_General_Preference_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link General Preference To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked General Preferences</relationshipLabel>
    <relationshipName>Linked_General_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference__c</fullName>
    <formula>HYPERLINK('/' + Linked_General_Preference_From__c, Linked_General_Preference_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_General_Preference_To__c, Linked_General_Preference_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked General Preference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_From__c</fullName>
    <label>Linked General Preference From</label>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (From)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerLinkedGeneralPreference.cls
public  class TriggerHandlerLinkedGeneralPreference extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerLinkedGeneralPreference() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {
        if(RecursiveTriggerHandler.runOnce()){
            beforeLogic(Trigger.new);
        }
    }
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert() {}
    public override void afterUpdate() {}
    public override void afterDelete() {}
    public override void afterUndelete() {}
    
    private void beforeLogic(List<sObject> newLinkedGeneralPreferences){
        system.debug('beforeLogic');
        List<Linked_General_Preference__c> newLinkedGeneralPreferenceList = (List<Linked_General_Preference__c>) newLinkedGeneralPreferences;
       
        for(Linked_General_Preference__c linkedGp : newLinkedGeneralPreferenceList){
            system.debug('linkedGp1: ' + linkedGp);
            
            //Create new general preference logic
            if (linkedGp.Link_General_Preference_To__c != NULL) {
                for (General_Preferences__c fromGp : [SELECT Id,Account_Number__c,Airline_Seat_Preference__c,Avid_Wine_Collector__c,Car_Rental_Preferences__c,Gym__c,Member_of_Social_or_Athletic_Club__c,Notes_Summary__c,Notes__c,Password__c,Preferred_Means_of_Air_Travel__c,
                                                      Preferred_Seating_Class__c,RecordTypeId,Repeat_Orders__c,Room_Preference__c,Season_Ticket_Holder__c,Security_Q_A__c,Sports_Played__c,Status__c,Sub_Type__c,Type__c,Username__c,Vacation_Locale_Preference__c,Preferred_Vendor__c,
                                                      Wine_Cellar__c
                                                      FROM General_Preferences__c 
                                                      WHERE Id = :linkedGp.Linked_General_Preference_From__c LIMIT 1]) {
                                                          General_Preferences__c newGp = new General_Preferences__c();
                                                          newGp.Contact_Name__c = linkedGp.Link_General_Preference_To__c;
                                                          newGp.Account_Number__c = fromGp.Account_Number__c;
                                                          newGp.Airline_Seat_Preference__c = fromGp.Airline_Seat_Preference__c;
                                                          newGp.Avid_Wine_Collector__c = fromGp.Avid_Wine_Collector__c;
                                                          newGp.Car_Rental_Preferences__c = fromGp.Car_Rental_Preferences__c;
                                                          newGp.Gym__c = fromGp.Gym__c;
                                                          newGp.Member_of_Social_or_Athletic_Club__c = fromGp.Member_of_Social_or_Athletic_Club__c;
                                                          newGp.Notes_Summary__c = fromGp.Notes_Summary__c;
                                                          newGp.Notes__c = fromGp.Notes__c;
                                                          newGp.Password__c = fromGp.Password__c;
                                                          newGp.Preferred_Means_of_Air_Travel__c = fromGp.Preferred_Means_of_Air_Travel__c;
                                                          newGp.Preferred_Seating_Class__c = fromGp.Preferred_Seating_Class__c;
                                                          newGp.RecordTypeId = fromGp.RecordTypeId;
                                                          newGp.Repeat_Orders__c = fromGp.Repeat_Orders__c;
                                                          newGp.Room_Preference__c = fromGp.Room_Preference__c;
                                                          newGp.Season_Ticket_Holder__c = fromGp.Season_Ticket_Holder__c;
                                                          newGp.Security_Q_A__c = fromGp.Security_Q_A__c;
                                                          newGp.Sports_Played__c = fromGp.Sports_Played__c;
                                                          newGp.Status__c = fromGp.Status__c;
                                                          newGp.Sub_Type__c = fromGp.Sub_Type__c;
                                                          newGp.Type__c = fromGp.Type__c;
                                                          newGp.Username__c = fromGp.Username__c;
                                                          newGp.Vacation_Locale_Preference__c = fromGp.Vacation_Locale_Preference__c;
                                                          newGp.Preferred_Vendor__c = fromGp.Preferred_Vendor__c;
                                                          newGp.Wine_Cellar__c = fromGp.Wine_Cellar__c;
                                                          insert newGp; 
                                                          system.debug('newGp: ' + newGp);
                                                          linkedGp.Linked_General_Preference_To__c = newGp.Id;
                                                          system.debug('newGp2: ' + newGp);
                                                      }
            } else if (linkedGp.Linked_General_Preference_To__c != NULL) { //link to existing general preference logic so sync
                for (General_Preferences__c fromGp : [SELECT Id,Account_Number__c,Airline_Seat_Preference__c,Avid_Wine_Collector__c,Car_Rental_Preferences__c,Gym__c,Member_of_Social_or_Athletic_Club__c,Notes_Summary__c,Notes__c,Password__c,Preferred_Means_of_Air_Travel__c,
                                                      Preferred_Seating_Class__c,RecordTypeId,Repeat_Orders__c,Room_Preference__c,Season_Ticket_Holder__c,Security_Q_A__c,Sports_Played__c,Status__c,Sub_Type__c,Type__c,Username__c,Vacation_Locale_Preference__c,Preferred_Vendor__c,
                                                      Wine_Cellar__c
                                                      FROM General_Preferences__c 
                                                      WHERE Id = :linkedGp.Linked_General_Preference_From__c LIMIT 1]) {
                                                          General_Preferences__c syncGp = new General_Preferences__c(Id = linkedGp.Linked_General_Preference_To__c);
                                                          syncGp.Account_Number__c = fromGp.Account_Number__c;
                                                          syncGp.Airline_Seat_Preference__c = fromGp.Airline_Seat_Preference__c;
                                                          syncGp.Avid_Wine_Collector__c = fromGp.Avid_Wine_Collector__c;
                                                          syncGp.Car_Rental_Preferences__c = fromGp.Car_Rental_Preferences__c;
                                                          syncGp.Gym__c = fromGp.Gym__c;
                                                          syncGp.Member_of_Social_or_Athletic_Club__c = fromGp.Member_of_Social_or_Athletic_Club__c;
                                                          syncGp.Notes_Summary__c = fromGp.Notes_Summary__c;
                                                          syncGp.Notes__c = fromGp.Notes__c;
                                                          syncGp.Password__c = fromGp.Password__c;
                                                          syncGp.Preferred_Means_of_Air_Travel__c = fromGp.Preferred_Means_of_Air_Travel__c;
                                                          syncGp.Preferred_Seating_Class__c = fromGp.Preferred_Seating_Class__c;
                                                          syncGp.RecordTypeId = fromGp.RecordTypeId;
                                                          syncGp.Repeat_Orders__c = fromGp.Repeat_Orders__c;
                                                          syncGp.Room_Preference__c = fromGp.Room_Preference__c;
                                                          syncGp.Season_Ticket_Holder__c = fromGp.Season_Ticket_Holder__c;
                                                          syncGp.Security_Q_A__c = fromGp.Security_Q_A__c;
                                                          syncGp.Sports_Played__c = fromGp.Sports_Played__c;
                                                          syncGp.Status__c = fromGp.Status__c;
                                                          syncGp.Sub_Type__c = fromGp.Sub_Type__c;
                                                          syncGp.Type__c = fromGp.Type__c;
                                                          syncGp.Username__c = fromGp.Username__c;
                                                          syncGp.Vacation_Locale_Preference__c = fromGp.Vacation_Locale_Preference__c;
                                                          syncGp.Preferred_Vendor__c = fromGp.Preferred_Vendor__c;
                                                          syncGp.Wine_Cellar__c = fromGp.Wine_Cellar__c;
                                                          RecursiveTriggerHandler.isFirstTime = TRUE;
                                                          update syncGp; 
                                                          system.debug('syncGp: ' + syncGp);
                                                      }
            }
        }
    }
}