unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Past Client</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Prospect Not Interested/Ghosted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Cancellation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Policy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Policy</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Last_Day_of_Month__c</fullName>
    <formula>if(
MONTH(TODAY()) = 12, DATETIMEVALUE(TEXT(YEAR(TODAY())+1) &amp; "-" &amp; TEXT(MONTH(TODAY())+1) &amp; "-01 02:50:00"),
DATETIMEVALUE(TEXT(YEAR(TODAY())) &amp; "-" &amp; TEXT(MONTH(TODAY())+1) &amp; "-01 01:58:00")
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Day of Month</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Used for prospects and client records</description>
    <label>Client Account</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Vendor_Account.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Account</fullName>
    <active>true</active>
    <description>Used for vendor records</description>
    <label>Vendor Account - Restaurant</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Cancellation_Policy__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Policy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Policy</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Monthly_Billing__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monthly Billing</label>
    <referenceTo>Monthly_Billing__c</referenceTo>
    <relationshipLabel>Logbooks</relationshipLabel>
    <relationshipName>Logbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Time Log Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Number_in_Party__c.field-meta.xml
<CustomField>
    <fullName>Number_in_Party__c</fullName>
    <label>Number in Party</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Person_Using__c.field-meta.xml
<CustomField>
    <fullName>Person_Using__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Using</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logbooks (Person Using)</relationshipLabel>
    <relationshipName>Logbooks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Logbook Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alerts</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booking Platform/Just Called</fullName>
            </value>
            <value>
                <fullName>Closing Logbook</fullName>
            </value>
            <value>
                <fullName>ClouDNA Holding</fullName>
            </value>
            <value>
                <fullName>Confirmed Request - Contact</fullName>
            </value>
            <value>
                <fullName>Confirmed Request - Other</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Contact Denied</fullName>
            </value>
            <value>
                <fullName>Contact Ghosted</fullName>
            </value>
            <value>
                <fullName>Coronavirus</fullName>
            </value>
            <value>
                <fullName>Doesn’t Exist</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Never Tried For</fullName>
            </value>
            <value>
                <fullName>No Contact</fullName>
            </value>
            <value>
                <fullName>No One Used - Cancelled</fullName>
            </value>
            <value>
                <fullName>No One Used - Insider Filled</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pending Request</fullName>
            </value>
            <value>
                <fullName>Private Event/Buyout</fullName>
            </value>
            <value>
                <fullName>Taken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Requested_By_Someone_Else__c.field-meta.xml
<CustomField>
    <fullName>Requested_By_Someone_Else__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logbooks (Requested By)</relationshipLabel>
    <relationshipName>Logbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>That vendor is closed. Please select a new one.</errorMessage>
        <filterItems>
            <field>Account.Closed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Bookings</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/DiningReservation.recordType-meta.xml
<RecordType>
    <fullName>DiningReservation</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>Dining Reservation</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Billable_Time_Logged_MTD_hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_hours__c</fullName>
    <formula>Billable_Time_Logged_MTD_minutes__c / 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billable Time Logged MTD (hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Monthly_Billing__c/Monthly_Billing__c.object-meta.xml
<CustomObject>
    <label>Monthly Billing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Monthly Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Monthly_Billing__c/fields/Billable_Time_Logged_MTD_hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_hours__c</fullName>
    <label>Billable Time Logged MTD Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Monthly_Billing__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Monthly Billings</relationshipLabel>
    <relationshipName>Monthly_Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Monthly_Billing__c/fields/Last_Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Last_Day_of_Month__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Day of Month</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Monthly_Billing__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Billable_Time__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time__c</fullName>
    <formula>VALUE(TEXT(Multiplier__c)) *  Duration_Minutes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billable Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Date_Logged__c.field-meta.xml
<CustomField>
    <fullName>Date_Logged__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Logged</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdateMonthlyBillingTotalsBatchTest.cls
@isTest
private class UpdateMonthlyBillingTotalsBatchTest {
    
    @testSetup
    static void setup() {
        // Create test Account
        Account acc = new Account(
            Name = 'Practice Angus Kaplan Account'
        );
        // Try to get Client Account RecordType if it exists
        List<RecordType> clientRTs = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' 
                                     AND DeveloperName = 'Client_Account' LIMIT 1];
        if (!clientRTs.isEmpty()) {
            acc.RecordTypeId = clientRTs[0].Id;
        }
        // Set Account_Status__c if the field exists
        if (Schema.sObjectType.Account.fields.getMap().containsKey('Account_Status__c')) {
            acc.Account_Status__c = 'Client';
        }
        insert acc;
        
        // Create Vendor Account (required for Case Vendor__c field)
        Account vendorAcc = new Account(
            Name = 'Test Vendor Restaurant'
        );
        // Get Vendor_Account RecordType
        List<RecordType> vendorRTs = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' 
                                     AND DeveloperName = 'Vendor_Account' LIMIT 1];
        if (!vendorRTs.isEmpty()) {
            vendorAcc.RecordTypeId = vendorRTs[0].Id;
        }
        insert vendorAcc;
        
        // Create Contact (required MasterDetail for Time_Log__c)
        Contact con = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id
        );
        insert con;
        
        // Get DiningReservation RecordType for Case
        Id diningReservationRTId;
        try {
            diningReservationRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                .get('DiningReservation').getRecordTypeId();
        } catch (Exception e) {
            // If RecordType doesn't exist, use default
            System.debug('DiningReservation RecordType not found: ' + e.getMessage());
        }
        
        // Create Case (required lookup for Time_Log__c) with DiningReservation record type
        Case testCase = new Case(
            Subject = 'Test Case',
            AccountId = acc.Id,
            ContactId = con.Id,
            Status = 'New',  // Required: Logbook Status
            Requested_By_Someone_Else__c = con.Id,  // Required: Requested by (lookup to Contact)
            Person_Using__c = con.Id,  // Required: Person Using (lookup to Contact)
            Origin = 'Email',  // Required: Logbook Origin
            Number_in_Party__c = 2,  // Required for DiningReservation
            Date__c = Date.today(),  // Required for Reservation Details
            Vendor__c = vendorAcc.Id,  // Required: Vendor Account
            Cancellation_Policy__c = 'Test cancellation policy text'  // Required: Text field
        );
        
        // Set RecordType FIRST before setting restricted picklist fields
        if (diningReservationRTId != null) {
            testCase.RecordTypeId = diningReservationRTId;
        }
        
        // Note: Reason__c is not required when Status = 'New'
        
        insert testCase;
        
        // Get current month dates
        Date today = Date.today();
        Date firstDay = Date.newInstance(today.year(), today.month(), 1);
        Date lastDay = Date.newInstance(today.year(), today.month(), Date.daysInMonth(today.year(), today.month()));
        
        // Create current month billing record
        Monthly_Billing__c currentMonthBilling = new Monthly_Billing__c(
            Client_Account__c = acc.Id,
            Start_Date__c = firstDay,
            Last_Day_of_Month__c = lastDay,
            Billable_Time_Logged_MTD_hours__c = 0
        );
        insert currentMonthBilling;
        
        // Create previous month billing record (should NOT be updated)
        Date prevMonthFirst = firstDay.addMonths(-1);
        Date prevMonthLast = Date.newInstance(prevMonthFirst.year(), prevMonthFirst.month(), 
                                             Date.daysInMonth(prevMonthFirst.year(), prevMonthFirst.month()));
        Monthly_Billing__c prevMonthBilling = new Monthly_Billing__c(
            Client_Account__c = acc.Id,
            Start_Date__c = prevMonthFirst,
            Last_Day_of_Month__c = prevMonthLast,
            Billable_Time_Logged_MTD_hours__c = 5
        );
        insert prevMonthBilling;
        
        // Create time logs for current month
        // Billable_Time__c is a formula field (Multiplier__c * Duration_Minutes__c)
        // so we set the source fields instead
        List<Time_Log__c> timeLogs = new List<Time_Log__c>();
        for(Integer i = 0; i < 3; i++) {
            timeLogs.add(new Time_Log__c(
                Client__c = acc.Id,
                Contact__c = con.Id,
                Case__c = testCase.Id,
                Date_Logged__c = today,
                Multiplier__c = '1', // Multiplier of 1
                Duration_Minutes__c = 120 // 120 minutes = 2 hours (when Multiplier = 1)
            ));
        }
        insert timeLogs;
    }
    
    @isTest
    static void testBatchUpdatesCurrentMonthOnly() {
        Test.startTest();
        UpdateMonthlyBillingTotalsBatch batch = new UpdateMonthlyBillingTotalsBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();
        
        Date today = Date.today();
        Date firstDay = Date.newInstance(today.year(), today.month(), 1);
        Date lastDay = Date.newInstance(today.year(), today.month(), Date.daysInMonth(today.year(), today.month()));
        
        // Check current month billing was updated (3 logs × 2 hours = 6 hours)
        Monthly_Billing__c currentMonth = [
            SELECT Id, Billable_Time_Logged_MTD_hours__c 
            FROM Monthly_Billing__c 
            WHERE Start_Date__c = :firstDay 
            AND Last_Day_of_Month__c = :lastDay
            LIMIT 1
        ];
        System.assertEquals(6.00, currentMonth.Billable_Time_Logged_MTD_hours__c, 
                          'Current month should have 6 hours');
        
        // Check previous month billing was NOT changed
        Date prevMonthFirst = firstDay.addMonths(-1);
        Date prevMonthLast = Date.newInstance(prevMonthFirst.year(), prevMonthFirst.month(), 
                                             Date.daysInMonth(prevMonthFirst.year(), prevMonthFirst.month()));
        Monthly_Billing__c prevMonth = [
            SELECT Id, Billable_Time_Logged_MTD_hours__c 
            FROM Monthly_Billing__c 
            WHERE Start_Date__c = :prevMonthFirst
            AND Last_Day_of_Month__c = :prevMonthLast
            LIMIT 1
        ];
        System.assertEquals(5.00, prevMonth.Billable_Time_Logged_MTD_hours__c, 
                          'Previous month should still have 5 hours (unchanged)');
    }
    
    @isTest
    static void testSchedulable() {
        Test.startTest();
        UpdateMonthlyBillingTotalsBatch batch = new UpdateMonthlyBillingTotalsBatch();
        String cronExp = '0 0 2 * * ?'; // Every night at 2 AM
        System.schedule('Test Update Monthly Billing', cronExp, batch);
        Test.stopTest();
        
        // Verify job was scheduled
        List<CronTrigger> scheduledJobs = [
            SELECT Id, CronExpression, State 
            FROM CronTrigger 
            WHERE CronJobDetail.Name = 'Test Update Monthly Billing'
        ];
        System.assertEquals(1, scheduledJobs.size(), 'Job should be scheduled');
    }
    
    @isTest
    static void testBatchWithNoTimeLogs() {
        // Delete all time logs
        delete [SELECT Id FROM Time_Log__c];
        
        Test.startTest();
        UpdateMonthlyBillingTotalsBatch batch = new UpdateMonthlyBillingTotalsBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();
        
        Date today = Date.today();
        Date firstDay = Date.newInstance(today.year(), today.month(), 1);
        Date lastDay = Date.newInstance(today.year(), today.month(), Date.daysInMonth(today.year(), today.month()));
        
        // Check current month billing was updated to 0
        Monthly_Billing__c currentMonth = [
            SELECT Id, Billable_Time_Logged_MTD_hours__c 
            FROM Monthly_Billing__c 
            WHERE Start_Date__c = :firstDay 
            AND Last_Day_of_Month__c = :lastDay
            LIMIT 1
        ];
        System.assertEquals(0.00, currentMonth.Billable_Time_Logged_MTD_hours__c, 
                          'Current month should have 0 hours when no time logs');
    }
}