unpackaged/main/default/objects/Account/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Time Log Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Travel_Planning.recordType-meta.xml
<RecordType>
    <fullName>Travel_Planning</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>Travel Planning</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Anniversary__c.field-meta.xml
<CustomField>
    <fullName>Anniversary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Anniversary</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Date_Logged__c.field-meta.xml
<CustomField>
    <fullName>Date_Logged__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Logged</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/RunTimeLogRollupForCaseTest.cls
@isTest
public class RunTimeLogRollupForCaseTest {
	@isTest 
    static void testRunTimeLogRollupForCase() {
        Test.StartTest();
         
         Account newAccount = new Account();
         newAccount.Name = 'Test';
         newAccount.Hours_per_Month__c = 1;
         insert newAccount;
        
         Contact newContact = new Contact();
         newContact.AccountId = newAccount.Id;
         newContact.FirstName = 'Test';
         newContact.LastName = 'Test';
         newContact.Time_Logged_MTD_Minutes__c = 1;
         newContact.Billable_Time_Logged_MTD_minutes__c = 1;
      	 newContact.Anniversary__c = Date.today();
         newContact.Birthdate = Date.today();
		 insert newContact;
        
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Travel_Planning').getRecordTypeId();

        Case C = new Case();
        C.Subject = 'Child';
        C.AccountId = newAccount.Id;
        C.ContactId = newContact.Id;
        C.RecordTypeId = recordTypeId;
        INSERT C;
        
        Time_Log__c TL2 = new Time_Log__c();
        TL2.Client__c = newAccount.Id;
        TL2.Contact__c = newContact.Id;
        TL2.Case__c = C.Id;
        TL2.Duration_Minutes__c = 5;
        TL2.Multiplier__c = '2';
        TL2.Date_Logged__c = Date.today();
        INSERT TL2;
        
        TL2.Duration_Minutes__c = 6;
        TL2.Case__c = C.Id;
        UPDATE TL2;      
        RunTimeLogRollupForCase.InputWrapper iw = new RunTimeLogRollupForCase.InputWrapper();
        iw.caseId = C.Id;
        List<RunTimeLogRollupForCase.InputWrapper> iwList = new List<RunTimeLogRollupForCase.InputWrapper>();
        iwList.add(iw);
        RunTimeLogRollupForCase.runBatch(iwList); 
        
        String sch ='0 48 * * * ?'; 
		System.schedule('Schedule to update Account Name', sch,new TimeLogRollupBatchScheduler());
        Test.StopTest();
    }
}