unpackaged/main/default/objects/Account/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Time_Logged_MTD__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Billable_Time__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time__c</fullName>
    <formula>VALUE(TEXT(Multiplier__c)) *  Duration_Minutes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billable Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/ThisMonth__c.field-meta.xml
<CustomField>
    <fullName>ThisMonth__c</fullName>
    <formula>MONTH(Date_Logged__c) = MONTH(DATEVALUE(NOW())) &amp;&amp; YEAR(Date_Logged__c) = YEAR(DATEVALUE(NOW()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ThisMonth</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TimeLogRecalc_Batch.cls
global class TimeLogRecalc_Batch implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext Bc){
        return Database.getQueryLocator([SELECT Id, AccountId, (SELECT Id, Duration_Minutes__c, Billable_Time__c, ThisMonth__c FROM Time_Logs__r WHERE ThisMonth__c = TRUE) 
                                         FROM Contact 
                                         WHERE Time_Logged_MTD_Minutes__c != null OR Billable_Time_Logged_MTD_minutes__c != null
                                         ORDER BY AccountId]);
    }

    global void execute(Database.BatchableContext Bc, List<Contact> scope){
        Savepoint sp = Database.setSavepoint();
        Set<Id> accountIds = new Set<Id>();
        List<Contact> contactsToUpdate = new List<Contact>();
        List<Account> accountsToUpdate = new List<Account>();
        
        try {
            for (Contact con :scope) {
                accountIds.add(con.AccountId);
                con.Time_Logged_MTD_Minutes__c = 0;
                con.Billable_Time_Logged_MTD_minutes__c = 0;
                Contact a = (Contact)con; //Grab the Account sObject - needed to avoid query locator error
                
                Time_Log__c[] tlList = a.getSObjects('Time_Logs__r'); //grab all the related Time_Log__c records
                if (tlList != null) { //if there are related Custom_Object_One__c record
                    for (Time_Log__c tl : tlList) {
                        if (tl.Duration_Minutes__c != null) {
                            con.Time_Logged_MTD_Minutes__c += tl.Duration_Minutes__c;
                        }
                        if (tl.Billable_Time__c != null) {
                            con.Billable_Time_Logged_MTD_minutes__c += tl.Billable_Time__c;
                        }
                    }
                }
                
                
                contactsToUpdate.add(con);
            }
            
            for (Id acctId :accountIds) {
                Account acct = new Account(
                    Id = acctId,
                    Time_Logged_MTD__c = 0,
                    Billable_Time_Logged_MTD_minutes__c = 0
                );
                for (Contact con :contactsToUpdate) {
                    if (acct.Id == con.AccountId) {
                        acct.Time_Logged_MTD__c += con.Time_Logged_MTD_Minutes__c;
                        acct.Billable_Time_Logged_MTD_minutes__c += con.Billable_Time_Logged_MTD_minutes__c;
                    }
                }
                accountsToUpdate.add(acct);
            }
            
            update contactsToUpdate;
            update accountsToUpdate;
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            Database.rollback(sp);
        }
    }
    
    global void finish(Database.BatchableContext Bc){

    }
}