unpackaged/main/default/objects/Account/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Time_Logged_MTD__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Billable_Time__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time__c</fullName>
    <formula>VALUE(TEXT(Multiplier__c)) *  Duration_Minutes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billable Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/ThisMonth__c.field-meta.xml
<CustomField>
    <fullName>ThisMonth__c</fullName>
    <formula>MONTH(Date_Logged__c) = MONTH(DATEVALUE(NOW())) &amp;&amp; YEAR(Date_Logged__c) = YEAR(DATEVALUE(NOW()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ThisMonth</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Util.cls
public class Util {
    public static void recalcContacts(Set<Id> contactIds){
        List<Contact> conList = [SELECT Id, Time_Logged_MTD_Minutes__c, Billable_Time_Logged_MTD_minutes__c, (SELECT Id, Contact__c, Duration_Minutes__c, Billable_Time__c FROM Time_Logs__r WHERE ThisMonth__c = TRUE) FROM Contact WHERE Id IN :contactIds];
              
        for (Contact con : conList) {
            con.Time_Logged_MTD_Minutes__c = 0;
            con.Billable_Time_Logged_MTD_minutes__c = 0;
            for (Time_Log__c tl : con.Time_Logs__r) {
                if (tl.Duration_Minutes__c != NULL) {
                    con.Time_Logged_MTD_Minutes__c += tl.Duration_Minutes__c;
                }
                if (tl.Billable_Time__c != NULL) {
                    con.Billable_Time_Logged_MTD_minutes__c += tl.Billable_Time__c;
                }
            }
        }
        
        update conList;
    }
    
    public static void recalcAccounts(Set<Id> accountIds){
        List<Account> accList = [SELECT Id, Time_Logged_MTD__c, Billable_Time_Logged_MTD_minutes__c, (SELECT Id, Client__c, Duration_Minutes__c, Billable_Time__c FROM Time_Logs__r WHERE ThisMonth__c = TRUE) FROM Account WHERE Id IN :accountIds];
              
        for (Account acc : accList) {
            acc.Time_Logged_MTD__c = 0;
            acc.Billable_Time_Logged_MTD_minutes__c = 0;
            for (Time_Log__c tl : acc.Time_Logs__r) {
                if (tl.Duration_Minutes__c != NULL) {
                    acc.Time_Logged_MTD__c += tl.Duration_Minutes__c;
                }
                if (tl.Billable_Time__c != NULL) {
                    acc.Billable_Time_Logged_MTD_minutes__c += tl.Billable_Time__c;
                }
            }
        }
        
        update accList;
    }

}