unpackaged/main/default/objects/Account/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Logbooks</relationshipLabel>
    <relationshipName>Logbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Time Log Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Anniversary__c.field-meta.xml
<CustomField>
    <fullName>Anniversary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Anniversary</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Date_Logged__c.field-meta.xml
<CustomField>
    <fullName>Date_Logged__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Logged</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TimeLogsTest.cls
@isTest
private class TimeLogsTest { 
        
    @isTest 
    static void testChildAndUpdates() {
        Test.StartTest();
        Case C = new Case();
        C.Subject = 'Child';
        C.AccountId = newAccount.Id;
        C.ContactId = newContact.Id;
        INSERT C;
        
        Time_Log__c TL2 = new Time_Log__c();
        TL2.Client__c = newAccount.Id;
        TL2.Contact__c = newContact.Id;
        TL2.Case__c = C.Id;
        TL2.Duration_Minutes__c = 5;
        TL2.Multiplier__c = '2';
        TL2.Date_Logged__c = Date.today();
        INSERT TL2;
        
        TL2.Duration_Minutes__c = 6;
        TL2.Case__c = C.Id;
        UPDATE TL2;      
        
        TimeLogRecalc_Schedule sh1 = new TimeLogRecalc_Schedule();
        String sch = '0 0 23 * * ?'; system.schedule('Test Schedule', sch, sh1);
        TimeLogRecalc_Batch batch = new TimeLogRecalc_Batch();
        ID batchprocessid = Database.executeBatch(batch,50);   
        Test.StopTest();
    }
    
    @isTest 
    static void testAccountContactReparent() {
        Test.StartTest();
        Account accClone = newAccount.clone(false, true, false, false);
        insert accClone;
        Contact conClone = newContact.clone(false, true, false, false);
        insert conClone;

        Case C = new Case();
        C.Subject = 'Child';
        C.AccountId = newAccount.Id;
        C.ContactId = newContact.Id;
        INSERT C;
        
        Time_Log__c TL2 = new Time_Log__c();
        TL2.Client__c = newAccount.Id;
        TL2.Contact__c = newContact.Id;
        TL2.Case__c = C.Id;
        TL2.Duration_Minutes__c = 5;
        TL2.Multiplier__c = '2';
        TL2.Date_Logged__c = Date.today().addDays(3);
        TL2.CreatedDate = Date.today();
        INSERT TL2;
        
        C.ParentId = newCase.Id;
        C.AccountId = accClone.Id;
        C.ContactId = conClone.Id;
        UPDATE C;
                
        Test.StopTest();
    }
    
    @isTest 
    static void testDeleteTimeLog() {
        Test.StartTest();
        DELETE newTimeLog;
        UNDELETE newTimeLog;
        Test.StopTest();
    }
    
    @isTest 
    static void testDeleteCase() {
        Test.StartTest();
        DELETE newCase;
        UNDELETE newCase;
        Test.StopTest();
    }
    
  	/***************************************************************************************************
                          Initialize Test Data
    **************************************************************************************************/    
    private static Insider_Team__c newInsiderTeam{
        get {
            if (newInsiderTeam == NULL ) {
                newInsiderTeam = new Insider_Team__c(
                    Name = 'Test Team'
                );
                insert newInsiderTeam;
            }
            return newInsiderTeam;
        }
        private set;
    }
    
    private static Account newAccount{
        get {
            if (newAccount == NULL ) {
                newAccount = new Account(
                   Name = 'Test',
                   Insider_Team__c = newInsiderTeam.Id,
                   Hours_per_Month__c = 1
                );
                insert newAccount;
            }
            return newAccount;
        }
        private set;
    }
    
    private static Contact newContact{
        get {
            if (newContact == NULL ) {
                newContact = new Contact(
                    AccountId = newAccount.Id,
                    FirstName = 'Test',
                    LastName = 'Test',
                    Time_Logged_MTD_Minutes__c = 1,
                    Billable_Time_Logged_MTD_minutes__c = 1,
                    Anniversary__c = Date.today(),
                    Birthdate = Date.today()
                );
                insert newContact;
            }
            return newContact;
        }
        private set;
    }
    
    private static Case newCase{
        get {
            if (newCase == NULL ) {
                newCase = new Case(
                    Subject = 'Case',
                    AccountId = newAccount.Id,
                    ContactId = newContact.Id
                );
                insert newCase;
            }
            return newCase;
        }
        private set;
    }
    
    private static Time_Log__c newTimeLog{
        get {
            if (newTimeLog == NULL ) {
                newTimeLog = new Time_Log__c(
                    Client__c = newAccount.Id,
                    Contact__c = newContact.Id,
                    Case__c = newCase.Id,
                    Duration_Minutes__c = 5,
                    Multiplier__c = '2',
                    Date_Logged__c = Date.today()
                );
                insert newTimeLog;
            }
            return newTimeLog;
        }
        private set;
    }
}