unpackaged/main/default/objects/Account/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Anniversary__c.field-meta.xml
<CustomField>
    <fullName>Anniversary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Anniversary</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Billable_Time_Logged_MTD_minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Logged_MTD_minutes__c</fullName>
    <label>Billable Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/ContactTest.cls
@isTest
public class ContactTest {
    
    @isTest 
    static void testChildAndUpdates() {
        Insider_Team__c newInsiderTeam = new Insider_Team__c(
            Name = 'Test Team'
        );
        insert newInsiderTeam;
        
        Account newAccount = new Account(
            Name = 'Test',
            Insider_Team__c = newInsiderTeam.Id,
            Hours_per_Month__c = 1
        );
        insert newAccount;
        
        Contact newContact = new Contact(
            AccountId = newAccount.Id,
            FirstName = 'Test',
            LastName = 'Test',
            Time_Logged_MTD_Minutes__c = 1,
            Billable_Time_Logged_MTD_minutes__c = 1,
            Anniversary__c = Date.today(),
            Birthdate__c = Date.today()
        );
        insert newContact;
        
        newContact.Anniversary__c = Date.today().addDays(1);
        newContact.Birthdate__c = Date.today().addDays(1);
        update newContact;
        newContact.Anniversary__c = NULL;
        newContact.Birthdate__c = NULL;
        update newContact;
    }
}