unpackaged/main/default/objects/Account/fields/Cross_Streets__c.field-meta.xml
<CustomField>
    <fullName>Cross_Streets__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cross Streets</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Neighbourhood__c.field-meta.xml
<CustomField>
    <fullName>Neighbourhood__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Neighborhood</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Address_Country__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Country</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Address_Street__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Address_Zip_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Zip Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Cross_Streets__c.field-meta.xml
<CustomField>
    <fullName>Cross_Streets__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cross Streets</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Doorman__c.field-meta.xml
<CustomField>
    <fullName>Doorman__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Doorman</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Facility_Manager__c.field-meta.xml
<CustomField>
    <fullName>Facility_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses (Facility Manager)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Neighbourhood__c.field-meta.xml
<CustomField>
    <fullName>Neighbourhood__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Neighbourhood</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Vacation Home</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
                <isActive>false</isActive>
                <label>Cottage</label>
            </value>
            <value>
                <fullName>Family Home</fullName>
                <isActive>false</isActive>
                <label>Family Home</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>This would be last resort to put in related notes that don't have a field</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/Linked_Address__c.object-meta.xml
<CustomObject>
    <label>Linked Address</label>
    <nameField>
        <displayFormat>LA-{0}</displayFormat>
        <label>Linked Addresse #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Address__c/fields/Link_Address_To__c.field-meta.xml
<CustomField>
    <fullName>Link_Address_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is just used to initially do the cloning</description>
    <label>Link Address To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked Addresses</relationshipLabel>
    <relationshipName>Linked_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address__c</fullName>
    <formula>HYPERLINK('/' + Linked_Address_From__c, Linked_Address_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Address_To__c, Linked_Address_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_From__c</fullName>
    <label>Linked Address From</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses (From)</relationshipLabel>
    <relationshipName>Linked_Addresses_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This address will initially be synced to the address selected here. Then they will be synced up whenever either address is updated.</inlineHelpText>
    <label>Linked Address To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Address_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses</relationshipLabel>
    <relationshipName>Linked_Addresses_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AddressTest.cls
@isTest
private class AddressTest { 
        
    @isTest 
    static void testTriggers() {
        Test.StartTest();
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A = new Account();
        A.Name = 'Test';
        A.Insider_Team__c = IT.Id;
        A.Hours_per_Month__c = 1;
        INSERT A;
        
        Contact conA = new Contact();
        conA.AccountId = A.Id;
        conA.FirstName = 'Test1';
        conA.LastName = 'Test2';
        INSERT conA;
        
        Contact conB = new Contact();
        conB.AccountId = A.Id;
        conB.FirstName = 'Test2';
        conB.LastName = 'Test2';
        INSERT conB;
        
        Address__c addA = new Address__c();
        addA.Contact_Name__c = conA.Id;
        addA.Address_City__c = 'Toronto';
        addA.Address_Country__c = 'Canada';
        addA.Address_State__c = 'NY';
        addA.Address_Street__c = '123 Fake Street';
        addA.Address_Zip_Code__c = '12345';
        addA.Cross_Streets__c = '123 x 345';
        addA.Doorman__c = TRUE;
        addA.Facility_Manager__c = conB.Id;
        addA.Neighbourhood__c = '3';
        addA.Notes__c = '4';
        addA.Primary__c = TRUE;
        addA.Type__c = 'Work';
        addA.Active__c = TRUE;
        INSERT addA;
        
        Address__c addB = addA.clone(false,false,false,false);
        addB.Contact_Name__c = conB.Id;
        INSERT addB;
        
        Address__c addC = addA.clone(false,false,false,false);
        INSERT addC;
        
        Linked_Address__c linkedAdd1 = new Linked_Address__c(Linked_Address_From__c = addA.Id, Link_Address_To__c = conB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd1;
        
        Linked_Address__c linkedAdd2 = new Linked_Address__c(Linked_Address_From__c = addA.Id, Linked_Address_To__c = addB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd2;
        
        Linked_Address__c linkedAdd3 = new Linked_Address__c(Linked_Address_From__c = addB.Id, Linked_Address_To__c = addC.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd3;
        
        addC.Address_City__c = 'Toronto';
        RecursiveTriggerHandler.isFirstTime = TRUE;
        update addC;
        
        LinkedAddressController controller = new LinkedAddressController();
        LinkedAddressController.getLinkedAddresses(addA.Id);

        RecursiveTriggerHandler.isFirstTime = TRUE;
        addA.Active__c = FALSE;
        addA.Inactive_Reason__c = 'test';
        UPDATE addA;
        
        DELETE linkedAdd1;
        Test.StopTest();
    }
}