unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>This would be last resort to put in related notes that don't have a field</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/General_Preferences__c.object-meta.xml
<CustomObject>
    <label>General Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferences/Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/General_Preferences__c/fields/Airline_Seat_Preference__c.field-meta.xml
<CustomField>
    <fullName>Airline_Seat_Preference__c</fullName>
    <label>Airline Seat Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Aisle</fullName>
            </value>
            <value>
                <fullName>Window</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>General Preferences</relationshipLabel>
    <relationshipName>Client_PreferencesContact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Gym__c.field-meta.xml
<CustomField>
    <fullName>Gym__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gym</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Member_of_Social_or_Athletic_Club__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Social_or_Athletic_Club__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Member of Social or Athletic Club</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Means_of_Air_Travel__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Means_of_Air_Travel__c</fullName>
    <label>Preferred Means of Air Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Preferred_Seating_Class__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Seating_Class__c</fullName>
    <label>Preferred Seating Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy Plus</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Repeat_Orders__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Orders__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Repeat Orders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/fields/Room_Preference__c.field-meta.xml
<CustomField>
    <fullName>Room_Preference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Preference</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/General_Preferences__c/recordTypes/Airline_and_Flight_Preferences.recordType-meta.xml
<RecordType>
    <fullName>Airline_and_Flight_Preferences</fullName>
    <active>true</active>
    <label>Airline Preferences</label>
</RecordType>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/Linked_General_Preference__c.object-meta.xml
<CustomObject>
    <label>Linked General Preference</label>
    <nameField>
        <displayFormat>LGP-{0}</displayFormat>
        <label>Linked General Preference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked General Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Link_General_Preference_To__c.field-meta.xml
<CustomField>
    <fullName>Link_General_Preference_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link General Preference To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked General Preferences</relationshipLabel>
    <relationshipName>Linked_General_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference__c</fullName>
    <formula>HYPERLINK('/' + Linked_General_Preference_From__c, Linked_General_Preference_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_General_Preference_To__c, Linked_General_Preference_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked General Preference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_From__c</fullName>
    <label>Linked General Preference From</label>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (From)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_General_Preference__c/fields/Linked_General_Preference_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_General_Preference_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This general preference will initially be synced to the general preference selected here. Then they will be synced up whenever either general preference is updated.</inlineHelpText>
    <label>Linked General Preference To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_General_Preference_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>General_Preferences__c</referenceTo>
    <relationshipLabel>Linked General Preferences (To)</relationshipLabel>
    <relationshipName>Linked_General_Preferences_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GeneralPreferenceTest.cls
@isTest
private class GeneralPreferenceTest { 
        
    @isTest 
    static void testTriggers() {
        Test.StartTest();
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A = new Account();
        A.Name = 'Test';
        A.Insider_Team__c = IT.Id;
        A.Hours_per_Month__c = 1;
        INSERT A;
        
        Contact conA = new Contact();
        conA.AccountId = A.Id;
        conA.FirstName = 'Test1';
        conA.LastName = 'Test2';
        INSERT conA;
        
        Contact conB = new Contact();
        conB.AccountId = A.Id;
        conB.FirstName = 'Test2';
        conB.LastName = 'Test2';
        INSERT conB;
        
        General_Preferences__c addA = new General_Preferences__c();
        addA.Contact_Name__c = conA.Id;
        addA.Account_Number__c = '123';
        addA.Airline_Seat_Preference__c = 'Middle';
        addA.Avid_Wine_Collector__c = TRUE;
        addA.Gym__c = A.Id;
        addA.Member_of_Social_or_Athletic_Club__c = 'Test';
        addA.Notes__c = 'Test';
        addA.Password__c = '123';
        addA.Preferred_Means_of_Air_Travel__c = 'Commercial';
        addA.Preferred_Seating_Class__c = 'Economy';
        addA.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'General_Preferences__c' AND DeveloperName = 'Airline_and_Flight_Preferences' LIMIT 1].Id;
        addA.Repeat_Orders__c = 'Test';
        addA.Room_Preference__c = 'Test';
        INSERT addA;
        
        General_Preferences__c addB = addA.clone(false,false,false,false);
        addB.Contact_Name__c = conB.Id;
        INSERT addB;
        
        General_Preferences__c addC = addA.clone(false,false,false,false);
        INSERT addC;
        
        Linked_General_Preference__c linkedAdd1 = new Linked_General_Preference__c(Linked_General_Preference_From__c = addA.Id, Link_General_Preference_To__c = conB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd1;
        
        Linked_General_Preference__c linkedAdd2 = new Linked_General_Preference__c(Linked_General_Preference_From__c = addA.Id, Linked_General_Preference_To__c = addB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd2;
        
        Linked_General_Preference__c linkedAdd3 = new Linked_General_Preference__c(Linked_General_Preference_From__c = addB.Id, Linked_General_Preference_To__c = addC.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd3;
        
        addC.Room_Preference__c = 'Test2';
        RecursiveTriggerHandler.isFirstTime = TRUE;
        update addC;
        
        LinkedGeneralPreferenceController controller = new LinkedGeneralPreferenceController();
        LinkedGeneralPreferenceController.getLinkedGeneralPreferences(addA.Id);

        RecursiveTriggerHandler.isFirstTime = TRUE;
        addA.Repeat_Orders__c = 'Test3';
        UPDATE addA;
        
        DELETE linkedAdd1;
        Test.StopTest();
    }
}