unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please only add exceptions, meaning vendor does not take AMEX or vendor will only take cash.</inlineHelpText>
    <label>Payment Method</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/Linked_Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Linked Payment Method</label>
    <nameField>
        <displayFormat>LPM-{0}</displayFormat>
        <label>Linked Payment Method #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Link_Payment_Method_To__c.field-meta.xml
<CustomField>
    <fullName>Link_Payment_Method_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is just used to initially do the cloning</description>
    <label>Link Payment Method To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked Payment Methods</relationshipLabel>
    <relationshipName>Linked_Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method__c</fullName>
    <formula>HYPERLINK('./' + Linked_Payment_Method_From__c, Linked_Payment_Method_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('./' + Linked_Payment_Method_To__c, Linked_Payment_Method_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Payment Method</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method_From__c</fullName>
    <label>Linked Payment Method From</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Linked Payment Methods (From)</relationshipLabel>
    <relationshipName>Linked_Payment_Methods_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This payment method will initially be synced to the payment method selected here. Then they will be synced up whenever either payment method is updated.</inlineHelpText>
    <label>Linked Payment Method To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Payment_Method_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Linked Payment Methods (To)</relationshipLabel>
    <relationshipName>Linked_Payment_Methods_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment_Method__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Credit_Card_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Number_Encrypted__c</fullName>
    <label>Credit Card Number</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Inactive_Reason__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inactive Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <formula>Client__r.Account.Insider_Team__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insider Team</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PaymentMethodTest.cls
@isTest
private class PaymentMethodTest {
    @isTest 
    static void tests() {        
        Test.StartTest();
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A = new Account();
        A.Name = 'Test';
        A.Insider_Team__c = IT.Id;
        A.Hours_per_Month__c = 1;
        INSERT A;
        
        Contact conA = new Contact();
        conA.AccountId = A.Id;
        conA.FirstName = 'Test1';
        conA.LastName = 'Test2';
        INSERT conA;
        
        Contact conB = new Contact();
        conB.AccountId = A.Id;
        conB.FirstName = 'Test2';
        conB.LastName = 'Test2';
        INSERT conB;
        
        Payment_Method__c pmA = new Payment_Method__c();
        pmA.Name = 'Test';
        pmA.Type__c = 'Business';
        pmA.Credit_Card_Number_Encrypted__c = '41111111111111111';
        INSERT pmA;

        Payment_Method__c pmB = pmA.clone(false,false,false,false);
        pmB.Client__c = conB.Id;
        INSERT pmB;
        
        Payment_Method__c pmC = pmA.clone(false,false,false,false);
        INSERT pmC;
        
        Linked_Payment_Method__c linkedPm1 = new Linked_Payment_Method__c(Linked_Payment_Method_From__c = pmA.Id, Link_Payment_Method_To__c = conB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedPm1;
        
        Linked_Payment_Method__c linkedPm2 = new Linked_Payment_Method__c(Linked_Payment_Method_From__c = pmA.Id, Linked_Payment_Method_To__c = pmB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedPm2;
        
        Linked_Payment_Method__c linkedPm3 = new Linked_Payment_Method__c(Linked_Payment_Method_From__c = pmB.Id, Linked_Payment_Method_To__c = pmC.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedPm3;
        

        pmA.Credit_Card_Number_Encrypted__c = '';
        RecursiveTriggerHandler.isFirstTime = TRUE;
        UPDATE pmA;
        
        LinkedPaymentMethodController controller = new LinkedPaymentMethodController();
        LinkedPaymentMethodController.getLinkedPaymentMethods(pmA.Id);

        RecursiveTriggerHandler.isFirstTime = TRUE;
        pmA.Active__c = FALSE;
        pmA.Inactive_Reason__c = 'test';
        UPDATE pmA;
        
        DELETE linkedPm1;
        Test.StopTest();
    }
}