unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>This would be last resort to put in related notes that don't have a field</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/Hates__c.object-meta.xml
<CustomObject>
    <label>Hate</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Hates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hates__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Airline_Seat_Hate__c.field-meta.xml
<CustomField>
    <fullName>Airline_Seat_Hate__c</fullName>
    <label>Airline Seat Hate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Aisle</fullName>
            </value>
            <value>
                <fullName>Window</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Avid_Wine_Collector__c.field-meta.xml
<CustomField>
    <fullName>Avid_Wine_Collector__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Avid Wine Collector</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hates</relationshipLabel>
    <relationshipName>Client_HatesContact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Gym__c.field-meta.xml
<CustomField>
    <fullName>Gym__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gym</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Hates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated_Means_of_Air_Travel__c.field-meta.xml
<CustomField>
    <fullName>Hated_Means_of_Air_Travel__c</fullName>
    <label>Hated Means of Air Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated_Seating_Class__c.field-meta.xml
<CustomField>
    <fullName>Hated_Seating_Class__c</fullName>
    <label>Hated Seating Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy Plus</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Member_of_Social_or_Athletic_Club__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Social_or_Athletic_Club__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Member of Social or Athletic Club</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Room_Hate__c.field-meta.xml
<CustomField>
    <fullName>Room_Hate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Hate</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/recordTypes/Airline_and_Flight_Hates.recordType-meta.xml
<RecordType>
    <fullName>Airline_and_Flight_Hates</fullName>
    <active>true</active>
    <label>Airline Hates</label>
</RecordType>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/Linked_Hate__c.object-meta.xml
<CustomObject>
    <label>Linked Hate</label>
    <nameField>
        <displayFormat>LH-{0}</displayFormat>
        <label>Linked Hate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Hates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Hate__c/fields/Link_Hate_To__c.field-meta.xml
<CustomField>
    <fullName>Link_Hate_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link Hate To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked Hates</relationshipLabel>
    <relationshipName>Linked_Hates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate__c</fullName>
    <formula>HYPERLINK('/' + Linked_Hate_From__c, Linked_Hate_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Hate_To__c, Linked_Hate_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Hate</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate_From__c</fullName>
    <label>Linked Hate From</label>
    <referenceTo>Hates__c</referenceTo>
    <relationshipLabel>Linked Hates (From)</relationshipLabel>
    <relationshipName>Linked_Hates_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Linked Hate To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Hate_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hates__c</referenceTo>
    <relationshipLabel>Linked Hates (Linked Hate To)</relationshipLabel>
    <relationshipName>Linked_Hates_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/HateTest.cls
@isTest
private class HateTest { 
        
    @isTest 
    static void testTriggers() {
        Test.StartTest();
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A = new Account();
        A.Name = 'Test';
        A.Insider_Team__c = IT.Id;
        A.Hours_per_Month__c = 1;
        INSERT A;
        
        Contact conA = new Contact();
        conA.AccountId = A.Id;
        conA.FirstName = 'Test1';
        conA.LastName = 'Test2';
        INSERT conA;
        
        Contact conB = new Contact();
        conB.AccountId = A.Id;
        conB.FirstName = 'Test2';
        conB.LastName = 'Test2';
        INSERT conB;
        
        Hates__c addA = new Hates__c();
        addA.Contact_Name__c = conA.Id;
        addA.Account_Number__c = '123';
        addA.Airline_Seat_Hate__c = 'Middle';
        addA.Avid_Wine_Collector__c = TRUE;
        addA.Gym__c = A.Id;
        addA.Member_of_Social_or_Athletic_Club__c = 'Test';
        addA.Notes__c = 'Test';
        addA.Password__c = '123';
        addA.Hated_Means_of_Air_Travel__c = 'Commercial';
        addA.Hated_Seating_Class__c = 'Economy';
        addA.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Hates__c' AND DeveloperName = 'Airline_and_Flight_Hates' LIMIT 1].Id;
        addA.Repeat_Orders__c = 'Test';
        addA.Room_Hate__c = 'Test';
        INSERT addA;
        
        Hates__c addB = addA.clone(false,false,false,false);
        addB.Contact_Name__c = conB.Id;
        INSERT addB;
        
        Hates__c addC = addA.clone(false,false,false,false);
        INSERT addC;
        
        Linked_Hate__c linkedAdd1 = new Linked_Hate__c(Linked_Hate_From__c = addA.Id, Link_Hate_To__c = conB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd1;
        
        Linked_Hate__c linkedAdd2 = new Linked_Hate__c(Linked_Hate_From__c = addA.Id, Linked_Hate_To__c = addB.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd2;
        
        Linked_Hate__c linkedAdd3 = new Linked_Hate__c(Linked_Hate_From__c = addB.Id, Linked_Hate_To__c = addC.Id);
        RecursiveTriggerHandler.isFirstTime = TRUE;
        INSERT linkedAdd3;
        
        addC.Room_Hate__c = 'Test2';
        RecursiveTriggerHandler.isFirstTime = TRUE;
        update addC;
        
        LinkedHateController controller = new LinkedHateController();
        LinkedHateController.getLinkedHates(addA.Id);

        RecursiveTriggerHandler.isFirstTime = TRUE;
        addA.Repeat_Orders__c = 'Test3';
        UPDATE addA;
        
        DELETE linkedAdd1;
        Test.StopTest();
    }
}