unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Zagat_Review__c.field-meta.xml
<CustomField>
    <fullName>Zagat_Review__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Review/Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Vendor_Account_Generic.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Account_Generic</fullName>
    <active>true</active>
    <label>Vendor Account - Generic</label>
</RecordType>

unpackaged/main/default/objects/Airline_Ticket__c/Airline_Ticket__c.object-meta.xml
<CustomObject>
    <label>Airline Ticket</label>
    <nameField>
        <displayFormat>PASS-{0000}</displayFormat>
        <label>Passenger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airline Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Airline_Ticket__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Airline Tickets</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Airline_Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <label>Flight #</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Flight_Booking__c.Logbook__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Flight_Booking__c</referenceTo>
    <relationshipLabel>Airline Tickets</relationshipLabel>
    <relationshipName>Airline_Tickets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Confirmation Date and Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Booking_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Booking_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Booking Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Check_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Check_In_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Check In Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Check_Out_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Check_Out_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Check Out Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Departure_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Departure Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Destination_Arrival_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Destination_Arrival_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Destination Arrival Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Drop_Off_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Drop_Off_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Drop/Off Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Pick_Up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Pick_Up_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Pick Up Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Logbooks</relationshipLabel>
    <relationshipName>Logbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/DiningReservation.recordType-meta.xml
<RecordType>
    <fullName>DiningReservation</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>Dining Reservation</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/Flight_Booking__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Flight #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Flight_Booking__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot find airline.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Account - Generic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Logbook__c.field-meta.xml
<CustomField>
    <fullName>Logbook__c</fullName>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flight_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/CasesControllerTest.cls
@isTest
private class CasesControllerTest {
    static testMethod void CreateRecords() {        
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        Case P = new Case();
        P.Subject = 'Parent';
        P.AccountId = A1.Id;
        P.ContactId = CON.Id;
        INSERT P;
        
        Case C = new Case();
        C.Subject = 'Child';
        C.AccountId = A1.Id;
        C.ContactId = CON.Id;
        C.Confirmation_Date__c = DateTime.now();
        INSERT C;
        
        Case C1 = new Case();
        C1.Subject = 'Child';
        C1.AccountId = A1.Id;
        C1.ContactId = CON.Id;
        C1.ParentId = P.Id;
        C1.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'DiningReservation' LIMIT 1].Id;
        C1.Confirmation_Date__c = DateTime.now();
        C1.Date__c = System.today();
        INSERT C1;
        
        ContentNote cn = new ContentNote();
        cn.OwnerId = UserInfo.getUserId();
        cn.SharingPrivacy = 'N';
        cn.Title = 'Test';
        INSERT cn;
        
        
        //Testing content document trigger
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cn.Id;
        cdl.LinkedEntityId = C.Id;
        cdl.Visibility = 'AllUsers';
        INSERT cdl;
        
        cdl.ShareType = 'V';
        UPDATE cdl;
        Id batchJobId = Database.executeBatch(new ContentDocumentShare_batch(), 100);
        
        CasesController controller1 = new CasesController();
        CasesController.getRelatedConfirmedCases(P.Id);
        
        Flight_Booking__c fb1 = new Flight_Booking__c();
        fb1.Name = 'Test 1';
        fb1.Logbook__c = C.Id;
        fb1.Airline__c = A2.Id;
        INSERT fb1;
        
        Flight_Booking__c fb2 = new Flight_Booking__c();
        fb2.Name = 'Test 1';
        fb2.Logbook__c = C.Id;
        fb2.Airline__c = A2.Id;
        
        Flight_Booking__c fb3 = [Select Id, Name, Airline__c FROM Flight_Booking__c WHERE Id = :fb1.Id];
            
        Airline_Ticket__c at = new Airline_Ticket__c();
        at.Flight__c = fb1.Id;
        at.Case__c = C.Id;
        INSERT at;
        
        List<Airline_Ticket__c> atList1 = new List<Airline_Ticket__c>();
        atList1.add(at);
        
        List<Airline_Ticket__c> atList2 = new List<Airline_Ticket__c>();
        atList2.add(at.clone(false, false, false, false));  

        CloneFlights controller2 = new CloneFlights();
        CloneFlights.cloneFlightFields(fb1.Id, JSON.serialize(fb3));
        CloneFlights.getAirlineTickets(fb1.Id);
        CloneFlights.cloneAirlineTickets(fb1.Id, fb2, atList1, atList2);
        CloneFlights.getFieldset();
        
        flightBookingData controller3 = new flightBookingData();
        controller3.csID = C.Id;
        String str = controller3.passengerNames;
    }
    static testMethod void testSetTime_AllFieldsChanged() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Destination_Arrival_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
    static testMethod void testSetTime_AllFieldsChanged1() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Booking_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
    static testMethod void testSetTime_AllFieldsChanged2() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Check_In_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
    static testMethod void testSetTime_AllFieldsChanged3() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Check_Out_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
    static testMethod void testSetTime_AllFieldsChanged4() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Departure_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
    static testMethod void testSetTime_AllFieldsChanged5() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Drop_Off_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
    static testMethod void testSetTime_AllFieldsChanged6() {
        // Create datetime values
        DateTime originalDT = DateTime.newInstance(2025, 7, 13, 10, 0, 0);
        DateTime updatedDT = DateTime.newInstance(2025, 7, 14, 12, 30, 0);

        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        
        
        // Old Case (simulate old values)
        // New Case (simulate updated flow values)
        Case newCase = new Case(
            Flow_Destination_Arrival_Date_Time__c = updatedDT,
            Flow_Booking_Date_Time__c = updatedDT,
            Flow_Check_In_Date_Time__c = updatedDT,
            Flow_Check_Out_Date_Time__c = updatedDT,
            Flow_Departure_Date_Time__c = updatedDT,
            Flow_Drop_Off_Date_Time__c = updatedDT,
            Flow_Pick_Up_Date_Time__c = updatedDT,
            AccountId = A1.Id,
            ContactId = CON.Id
        );
		Insert newCase;
        
        // Simulate calling the private method by wrapping it in a public method in your handler class
        Test.startTest();
        newCase.Flow_Pick_Up_Date_Time__c = system.today();
        update newCase;
        Test.stopTest();

        // Assert that split fields are correctly set
      }
}