unpackaged/main/default/objects/Account/fields/Hours_per_Month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_Month__c</fullName>
    <label>Hours per Month</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Zagat_Review__c.field-meta.xml
<CustomField>
    <fullName>Zagat_Review__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Review/Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Vendor_Account_Generic.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Account_Generic</fullName>
    <active>true</active>
    <label>Vendor Account - Generic</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Confirmation Date and Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Logbooks</relationshipLabel>
    <relationshipName>Logbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Itinerary</label>
    <referenceTo>Itinerary__c</referenceTo>
    <relationshipLabel>Logbooks</relationshipLabel>
    <relationshipName>Logbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Refundable__c.field-meta.xml
<CustomField>
    <fullName>Refundable__c</fullName>
    <label>Refundable</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refundable</fullName>
            </value>
            <value>
                <fullName>Non-Refundable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>That vendor is closed. Please select a new one.</errorMessage>
        <filterItems>
            <field>Account.Closed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Bookings</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Flight_Booking_Single_Person.recordType-meta.xml
<RecordType>
    <fullName>Flight_Booking_Single_Person</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>Flight Booking</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_month__c</fullName>
    <label>Hours per Month</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Time_Logged_MTD_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Logged_MTD_Minutes__c</fullName>
    <label>Time Logged MTD (minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/Flight_Booking__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Flight #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Flight_Booking__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Logbook__c.field-meta.xml
<CustomField>
    <fullName>Logbook__c</fullName>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flight_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Refundable__c.field-meta.xml
<CustomField>
    <fullName>Refundable__c</fullName>
    <inlineHelpText>Fill out this field to replace logbook field</inlineHelpText>
    <label>Refundable</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Refundable</fullName>
            </value>
            <value>
                <fullName>Non-Refundable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Itinerary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Itinerary__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Itinerary__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Itinerary__c/fields/Intro_Picture__c.field-meta.xml
<CustomField>
    <fullName>Intro_Picture__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Intro Picture</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Itinerary__c/fields/Logbook__c.field-meta.xml
<CustomField>
    <fullName>Logbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Itinerary__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <displayFormat>PN-{0000000}</displayFormat>
        <label>Passenger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Passenger__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Passenger__c/fields/Logbook__c.field-meta.xml
<CustomField>
    <fullName>Logbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ItineraryTemplateController2Test.cls
/* 
    * Class Name : ItineraryTemplateController2Test
    * Description : Test Class for ItineraryTemplateController2.
    * Created Date : 11/09/2023
*/
@isTest
private class ItineraryTemplateController2Test {
    /* ***********************************************************************************************************************        
        @Method_Name : createData       
        @Method_Description : Method is used to generate data.    
    ************************************************************************************************************************** */
    @TestSetup
    static void createData() {        
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team';
        INSERT IT;
        
        Account A1 = new Account();
        A1.Name = 'Test';
        A1.Insider_Team__c = IT.Id;
        A1.Hours_per_Month__c = 1;
        A1.Zagat_Review__c = 'asdasdasd \n sdasda';
        INSERT A1;
        
        Account A2 = new Account();
        A2.Name = 'Test';
        A2.Insider_Team__c = IT.Id;
        A2.Hours_per_Month__c = 1;
        A2.Zagat_Review__c = 'asdasdasd \n sdasda';
        A2.RecordTypeId = [Select Id, Name, DeveloperName From RecordType WHERE DeveloperName = 'Vendor_Account_Generic'].Id;
        INSERT A2;

        A2.Zagat_Review__c = NULL;
        UPDATE A2;
        
        Contact CON = new Contact();
        CON.AccountId = A1.Id;
        CON.FirstName = 'Test';
        CON.LastName = 'Test';
        CON.Time_Logged_MTD_Minutes__c = 1;        
        INSERT CON;
        

        Case P = new Case();
        P.Subject = 'Parent';
        P.AccountId = A1.Id;
        P.ContactId = CON.Id;
        P.Date__c = System.today();
        P.Description = 'qwertyuiop';
        P.Description__c = 'Its just a description.';
        P.Subject = 'Test';
        P.Check_In_Date__c = System.today();
        P.Check_Out_Date__c = System.today()+1;
        P.Room_Type__c = 'Room';
        P.Vendor__c = A2.Id;
        P.Status = 'New';
        P.Origin = 'Email';
        INSERT P;
        
        Itinerary__c itV = new Itinerary__c();
        itV.Client__c = A1.Id;
        itV.End_Date__c = System.today();
        itV.Intro_Picture__c = 'dummy';
        itV.Name = 'Dummy';
        itV.Logbook__c = P.Id;
        itV.Start_Date__c = System.today();
        INSERT itV;
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Flight_Booking_Single_Person').getRecordTypeId();

        Case C = new Case();
        C.Subject = 'Child';
        C.AccountId = A1.Id;
        C.ContactId = CON.Id;
        C.Itinerary__c = itV.Id;
        C.Confirmation_Date__c = DateTime.now();
        C.RecordTypeId = recordTypeId;
        INSERT C;
        Case Ca = new Case();
        Ca.Subject = 'Child';
        Ca.AccountId = A1.Id;
        Ca.ContactId = CON.Id;
        Ca.Itinerary__c = itV.Id;
        Ca.Confirmation_Date__c = DateTime.now();
        INSERT Ca;

        Flight_Booking__c fb = new Flight_Booking__c();
        fb.Departure_Date__c = System.today();
        fb.Name = 'Test';
        fb.Refundable__c = 'true';
        fb.Logbook__c = C.Id;
        INSERT fb;

        Passenger__c ps = new Passenger__c();
        ps.Contact__c = CON.Id;
        ps.Logbook__c = C.Id;
        INSERT ps;

    }
    
    
    /* ***********************************************************************************************************************        
        @Method_Name : ItineraryTemplate_Test       
        @Method_Description : Method is used to test ItineraryTemplateController2 class.    
    ************************************************************************************************************************** */
    @IsTest 
    private static void ItineraryTemplate_Test() {
        Itinerary__c ca = [SELECT Id FROM Itinerary__c LIMIT 1];
        Test.StartTest(); 
            ApexPages.currentPage().getParameters().put('id', String.valueOf(ca.Id));
            ItineraryTemplateController2 testItineraryTemplateController = new ItineraryTemplateController2();
        Test.StopTest();
        Assert.areEqual(ca.Id, testItineraryTemplateController.currentRecordId);                      
        Assert.areEqual(ca.Id, testItineraryTemplateController.thisItinerary.Id);                      
        Assert.isNotNull(testItineraryTemplateController.metadataLogBooks);                      
        Assert.isNotNull(testItineraryTemplateController.relatedflightBooks);                                        
    }  
}