unpackaged/main/default/objects/Account/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Global_Setting__c/Global_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Global Settings</label>
</CustomObject>

unpackaged/main/default/objects/Global_Setting__c/fields/Insider_Account__c.field-meta.xml
<CustomField>
    <fullName>Insider_Account__c</fullName>
    <defaultValue>"0010b00002M9FU0AAN"</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Insider Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/SetupSandbox.cls
global class SetupSandbox implements SandboxPostCopy {
    global void runApexClass(SandboxContext context) {
        System.debug('Org ID: ' + context.organizationId());
        System.debug('Sandbox ID: ' + context.sandboxId());
        System.debug('Sandbox Name: ' + context.sandboxName());
        
        Insider_Team__c IT = new Insider_Team__c();
        IT.Name = 'Test Team 1';
        INSERT IT;
        
        Account A = new Account();
        A.Name = 'Insider';
        A.Insider_Team__c = IT.Id;
        INSERT A;
        
        Account B = new Account();
        B.Name = 'SimpCo';
        B.Insider_Team__c = IT.Id;
        INSERT B;
        
        Contact C = new Contact();
        C.FirstName = 'Homer';
        C.LastName = 'Simpson';
        C.AccountId = B.Id;
        INSERT C;

        Global_Setting__c GS = [SELECT Insider_Account__c FROM Global_Setting__c LIMIT 1];
        GS.Insider_Account__c = A.Id;
        UPDATE GS;
    }
}