unpackaged/main/default/objects/Case/fields/Case_Time_Logged__c.field-meta.xml
<CustomField>
    <fullName>Case_Time_Logged__c</fullName>
    <label>Case Time Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <label>Check In Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Time__c</fullName>
    <label>Check Out Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Date_of_Departure__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Departure__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/DateofBooking__c.field-meta.xml
<CustomField>
    <fullName>DateofBooking__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Booking</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Time__c</fullName>
    <label>Departure Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Destination_Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Destination_Arrival_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination Arrival Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Destination_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Destination_Arrival_Time__c</fullName>
    <label>Destination Arrival Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Drop_off_Date__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drop Off Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Drop_off_Time__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_Time__c</fullName>
    <label>Drop off Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Enter_Time__c.field-meta.xml
<CustomField>
    <fullName>Enter_Time__c</fullName>
    <label>Enter Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Booking_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Booking_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Booking Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Check_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Check_In_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Check In Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Check_Out_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Check_Out_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Check Out Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Departure_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Departure Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Destination_Arrival_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Destination_Arrival_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Destination Arrival Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Drop_Off_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Drop_Off_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Drop/Off Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Pick_Up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Flow_Pick_Up_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flow - Pick Up Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Hierarchical_Time_Logged__c.field-meta.xml
<CustomField>
    <fullName>Hierarchical_Time_Logged__c</fullName>
    <label>Hierarchical Time Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/House_Account__c.field-meta.xml
<CustomField>
    <fullName>House_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Logbooks (House Account)</relationshipLabel>
    <relationshipName>Logbooks_House_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/House_Contact__c.field-meta.xml
<CustomField>
    <fullName>House_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Logbooks (House Contact)</relationshipLabel>
    <relationshipName>Logbooks_House_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/House_Conversion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>House_Conversion_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>House Conversion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Time Log Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Multiplier_Reason__c.field-meta.xml
<CustomField>
    <fullName>Multiplier_Reason__c</fullName>
    <label>Time Log Multiplier Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left Office During Business Hours</fullName>
            </value>
            <value>
                <fullName>Requested After 6pm Before 10pm</fullName>
            </value>
            <value>
                <fullName>Weekend Non-Errand</fullName>
            </value>
            <value>
                <fullName>After 10 PM / Before 9 AM</fullName>
            </value>
            <value>
                <fullName>Weekend Errand</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Holiday Weekend</fullName>
            </value>
            <value>
                <fullName>Commission Earned/Not Charging Time</fullName>
            </value>
            <value>
                <fullName>Closing Logbook</fullName>
            </value>
            <value>
                <fullName>Last Minute Request</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Time for Closing Logbook</fullName>
                <isActive>false</isActive>
                <label>Time for Closing Logbook</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pick Up Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pickup_Time__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Time__c</fullName>
    <label>Pick Up Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Time_Description__c.field-meta.xml
<CustomField>
    <fullName>Time_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Time Log Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Time_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Time_of_Booking__c</fullName>
    <label>Time of Booking</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Date_Logged__c.field-meta.xml
<CustomField>
    <fullName>Date_Logged__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Logged</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Multiplier_Reason__c.field-meta.xml
<CustomField>
    <fullName>Multiplier_Reason__c</fullName>
    <label>Multiplier Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Left Office During Business Hours</fullName>
            </value>
            <value>
                <fullName>Requested After 6pm Before 10pm</fullName>
            </value>
            <value>
                <fullName>Weekend Non-Errand</fullName>
            </value>
            <value>
                <fullName>After 10 PM / Before 9 AM</fullName>
            </value>
            <value>
                <fullName>Weekend Errand</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Commission Earned/Not Charging Time</fullName>
            </value>
            <value>
                <fullName>Closing Logbook</fullName>
            </value>
            <value>
                <fullName>Holiday Weekend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerCase.cls
/*
*   PURPOSE:       This class will handle trigger behaviour and will perform task accordingly
*   INTERFACES:     
*   CHANGE LOG:    27-8-2018    Intial release 
*/
public class TriggerHandlerCase extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerCase() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {}
    public override void beforeUpdate() {
        //createTimeEntry(Trigger.new);
        setTime(Trigger.new, Trigger.oldMap);
        diningConversion(Trigger.new, Trigger.oldMap);
    }
    public override void beforeDelete() {}
    public override void afterInsert()  {}
    public override void afterUpdate()  {
        updateTimeLogParents(Trigger.new, Trigger.oldMap);
        recalcHierarchyTime(Trigger.new, Trigger.oldMap);
    }
    public override void afterDelete()  {
        recalcHierarchyTime(Trigger.new, Trigger.oldMap);
    }
    public override void afterUndelete(){
        recalcHierarchyTime(Trigger.new, Trigger.oldMap);
    }
    
    /*private void createTimeEntry(List<sObject> newCases){
        system.debug('createTimeEntry');
        List<Case> newCaseList = (List<Case>) newCases;
        List<Time_Log__c> newTimeLogs = new List<Time_Log__c>();

        for(Case cs : newCaseList){
            //oldMap.get(cs.Id).Status
            //cs.Status
            if (cs.Enter_Time__c != NULL) {
                Time_Log__c tl = new Time_Log__c(
                    Case__c = cs.Id,
                    Client__c = cs.AccountId,
                    Contact__c = cs.ContactId,
                    Duration_Minutes__c = cs.Enter_Time__c,
                    Comments__c = cs.Time_Description__c,
                    Date_Logged__c = Date.today(),
                    Multiplier_Reason__c = cs.Multiplier_Reason__c,
                    Multiplier__c = cs.Multiplier__c
                );
                newTimeLogs.add(tl);
                cs.Enter_Time__c = NULL;
                cs.Time_Description__c = NULL;
                cs.Multiplier__c = NULL;
                cs.Multiplier_Reason__c = NULL;
            }
        }
        insert newTimeLogs;
    }*/
    
    private void setTime(List<sObject> newCases , Map<Id,sObject> oldCaseMap){
        system.debug('setTime');
        List<Case> newCaseList = (List<Case>) newCases;
        
        if(oldCaseMap != NULL){
            Map<Id,Case> oldMap = (Map<Id,Case>) oldCaseMap;
            
            for(Case cs : newCaseList){
                if (cs.Flow_Destination_Arrival_Date_Time__c != NULL && cs.Flow_Destination_Arrival_Date_Time__c != oldMap.get(cs.Id).Flow_Destination_Arrival_Date_Time__c) {
                    system.debug('cs.Flow_Destination_Arrival_Date_Time__c: ' + cs.Flow_Destination_Arrival_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Destination_Arrival_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    cs.Destination_Arrival_Date__c = convertedDateTime.date();
                    cs.Destination_Arrival_Time__c = convertedDateTime.time();
                }
                
                if (cs.Flow_Booking_Date_Time__c != NULL && cs.Flow_Booking_Date_Time__c != oldMap.get(cs.Id).Flow_Booking_Date_Time__c) {
                    system.debug('cs.Flow_Booking_Date_Time__c: ' + cs.Flow_Booking_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Booking_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    cs.DateOfBooking__c = convertedDateTime.date();
                    cs.Time_of_Booking__c = convertedDateTime.time();
                }
                
                if (cs.Flow_Check_In_Date_Time__c != NULL && cs.Flow_Check_In_Date_Time__c != oldMap.get(cs.Id).Flow_Check_In_Date_Time__c) {
                    system.debug('cs.Flow_Check_In_Date_Time__c: ' + cs.Flow_Check_In_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Check_In_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    cs.Check_In_Date__c = convertedDateTime.date();
                    cs.Check_In_Time__c = convertedDateTime.time();
                }
                
                if (cs.Flow_Check_Out_Date_Time__c != NULL && cs.Flow_Check_Out_Date_Time__c != oldMap.get(cs.Id).Flow_Check_Out_Date_Time__c) {
                    system.debug('cs.Flow_Check_Out_Date_Time__c: ' + cs.Flow_Check_Out_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Check_Out_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    
                    cs.Check_Out_Date__c = convertedDateTime.date();
                    cs.Check_Out_Time__c = convertedDateTime.time();
                }
                
                if (cs.Flow_Departure_Date_Time__c != NULL && cs.Flow_Departure_Date_Time__c != oldMap.get(cs.Id).Flow_Departure_Date_Time__c) {
                    system.debug('cs.Flow_Departure_Date_Time__c: ' + cs.Flow_Departure_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Departure_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    
                    cs.Date_of_Departure__c = convertedDateTime.date();
                    cs.Departure_Time__c = convertedDateTime.time();
                }
                
                if (cs.Flow_Drop_Off_Date_Time__c != NULL && cs.Flow_Drop_Off_Date_Time__c != oldMap.get(cs.Id).Flow_Drop_Off_Date_Time__c) {
                    system.debug('cs.Flow_Drop_Off_Date_Time__c: ' + cs.Flow_Drop_Off_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Drop_Off_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    
                    cs.Drop_off_Date__c = convertedDateTime.date();
                    cs.Drop_off_Time__c = convertedDateTime.time();
                }
                
                if (cs.Flow_Pick_Up_Date_Time__c != NULL && cs.Flow_Pick_Up_Date_Time__c != oldMap.get(cs.Id).Flow_Pick_Up_Date_Time__c) {
                    system.debug('cs.Flow_Pick_Up_Date_Time__c: ' + cs.Flow_Pick_Up_Date_Time__c); 
                    DateTime convertedDateTime = DateTime.valueOf(cs.Flow_Pick_Up_Date_Time__c.format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().toString()));
                    system.debug('convertedDateTime: ' + convertedDateTime); 
                    
                    cs.Pickup_Date__c = convertedDateTime.date();
                    cs.Pickup_Time__c = convertedDateTime.time();
                }
            }
        }
    }
    
    private void diningConversion(List<sObject> newCases , Map<Id,sObject> oldCaseMap){
        system.debug('diningConversion');
        List<Case> newCaseList = (List<Case>) newCases;
        
        if(oldCaseMap != NULL){
            Map<Id,Case> oldMap = (Map<Id,Case>) oldCaseMap;
            
            for(Case cs : newCaseList){
                if (cs.RecordTypeId != oldMap.get(cs.Id).RecordTypeId && oldMap.get(cs.Id).RecordTypeId == '0120b000000hwtbAAA') {
                    cs.House_Contact__c = oldMap.get(cs.Id).ContactId;
                    cs.House_Account__c = oldMap.get(cs.Id).AccountId;
                    cs.House_Conversion_Date_Time__c = DateTime.now();
                }
            }
        }
    }
    
    private void updateTimeLogParents(List<sObject> newCases , Map<Id,sObject> oldCaseMap){
        system.debug('updateTimeLogParents');
        List<Case> newCaseList = (List<Case>) newCases;
        
        if(oldCaseMap != NULL){
            Map<Id,Case> oldMap = (Map<Id,Case>) oldCaseMap;
            Set<Id> caseIds = new Set<Id>();
            List<Time_Log__c> timeLogsToUpdate = new List<Time_Log__c>();
            
            for(Case cs : newCaseList){
                if (cs.AccountId != oldMap.get(cs.Id).AccountId || cs.ContactId != oldMap.get(cs.Id).ContactId) {
                    caseIds.add(cs.Id);
                }
            }
            for (Time_Log__c tl : [SELECT Id, Case__c, Case__r.AccountId, Case__r.ContactId, Case__r.Contact.FirstName, Client__c, Contact__c, CreatedDate 
                                   FROM Time_Log__c 
                                   WHERE Case__c IN :caseIds AND CreatedDate >= :Date.newInstance(2019, 09, 12)  ]) {
                                       tl.Client__c = tl.Case__r.AccountId;
                                       tl.Contact__c = tl.Case__r.ContactId;
                                       timeLogsToUpdate.add(tl);
                                       system.debug('tl: ' + tl.Case__r.Contact.FirstName);
            }
            
            if (!timeLogsToUpdate.isEmpty()) {
                update timeLogsToUpdate;
            }
        }
    }
    
    private void recalcHierarchyTime(List<sObject> newCases , Map<Id,sObject> oldCaseMap){
        system.debug('recalcHierarchyTime');
        List<Case> newCaseList = (List<Case>) newCases;

        Set<Id> contactIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        
        if(oldCaseMap != NULL){
            Map<Id,Case> oldMap = (Map<Id,Case>) oldCaseMap;
            Set<Id> caseIds = new Set<Id>();
            List<Case> casesToUpdate = new List<Case>();
			
            if (newCaseList == null) {
                for(Case cs : oldMap.values()){
                    caseIds.add(cs.ParentId);
                    
                    contactIds.add(cs.ContactId);
                    accountIds.add(cs.AccountId);
                }
            } else {
                for(Case cs : newCaseList){
                    //oldMap.get(cs.Id).Status
                    //cs.Status
                    if (cs.ParentId != oldMap.get(cs.Id).ParentId) {
                        if (cs.ParentId != NULL) {
                            caseIds.add(cs.ParentId);
                        }
                        if (oldMap.get(cs.Id).ParentId != NULL) {
                            caseIds.add(oldMap.get(cs.Id).ParentId);
                        }
                    }
                    
                    contactIds.add(cs.ContactId);
                    accountIds.add(cs.AccountId);
                    contactIds.add(oldMap.get(cs.Id).ContactId);
                    accountIds.add(oldMap.get(cs.Id).AccountId);
                }
            }
            
            system.debug('caseIds: ' + caseIds);
            if (caseIds.size() > 0) {
                casesToUpdate = [SELECT Id, ParentId, Hierarchical_Time_Logged__c, (SELECT Id, Case_Time_Logged__c FROM Cases) FROM Case WHERE Id IN :caseIds];
                for (Case parentCase : casesToUpdate) {
                    parentCase.Hierarchical_Time_Logged__c = 0;
                    for (Case childCase : parentCase.Cases) {
                        if (childCase.Case_Time_Logged__c != NULL) {
                            parentCase.Hierarchical_Time_Logged__c += childCase.Case_Time_Logged__c;
                        }
                    }
                }
                system.debug('casesToUpdate: ' + casesToUpdate);
                update casesToUpdate;
            }
            
            if (contactIds.size() > 0) {
                Util.recalcContacts(contactIds);
            }
            
            if (accountIds.size() > 0) {
                Util.recalcAccounts(accountIds);
            }
        }
    }
}