unpackaged/main/default/objects/Case/fields/Case_Time_Logged__c.field-meta.xml
<CustomField>
    <fullName>Case_Time_Logged__c</fullName>
    <label>Case Time Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Hierarchical_Time_Logged__c.field-meta.xml
<CustomField>
    <fullName>Hierarchical_Time_Logged__c</fullName>
    <label>Hierarchical Time Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Billable_Time__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time__c</fullName>
    <formula>VALUE(TEXT(Multiplier__c)) *  Duration_Minutes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billable Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration (Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/ParentLogbookId__c.field-meta.xml
<CustomField>
    <fullName>ParentLogbookId__c</fullName>
    <formula>Case__r.ParentId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ParentLogbookId</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerTimeLog.cls
/*
*   PURPOSE:       This class will handle trigger behaviour and will perform task accordingly
*/
public  class TriggerHandlerTimeLog extends TriggerHandler {    
    // Constructor 
    public TriggerHandlerTimeLog() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert()  {
        recalcCaseTimeLogs(Trigger.new, Trigger.oldMap);
    }
    public override void afterUpdate()  {
        recalcCaseTimeLogs(Trigger.new, Trigger.oldMap);
    }
    public override void afterDelete()  {
        recalcCaseTimeLogs(Trigger.new, Trigger.oldMap);
    }
    public override void afterUndelete(){
        recalcCaseTimeLogs(Trigger.new, Trigger.oldMap);
    }
    
    private void recalcCaseTimeLogs(List<sObject> newTimeLogs, Map<Id,sObject> oldTimeLogMap){
        system.debug('recalcCaseTimeLogs');
        
        List<Time_Log__c> newTimeLogsList = (List<Time_Log__c>) newTimeLogs;
        Map<Id,Time_Log__c> oldMap;
        
        if(oldTimeLogMap != NULL){
            oldMap = (Map<Id,Time_Log__c>) oldTimeLogMap;
        }
        
        Set<Id> caseIds = new Set<Id>();
        Set<Id> parentCaseIds = new Set<Id>();
        
        Set<Id> contactIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
                
        List<Case> casesToUpdate = new List<Case>();
        List<Case> parentCasesToUpdate = new List<Case>();
        
        if (newTimeLogsList == null) {
            for(Time_Log__c tl : oldMap.values()){
                caseIds.add(tl.Case__c);
                
                contactIds.add(tl.Contact__c);
                accountIds.add(tl.Client__c);
            }
        } else {
            for(Time_Log__c tl : newTimeLogsList){
                
                //oldMap.get(cs.Id).Status
                //cs.Status
                if (tl.Case__c != NULL) {
                    caseIds.add(tl.Case__c);
                }
                
                //check old cases
                if (oldMap != NULL) {
                    if (tl.Case__c != oldMap.get(tl.Id).Case__c) {
                        if (oldMap.get(tl.Id).Case__c != NULL) {
                            caseIds.add(oldMap.get(tl.Id).Case__c);
                        }
                    }
                }
                
                contactIds.add(tl.Contact__c);
                accountIds.add(tl.Client__c);
            }
        }
        
        system.debug('caseIds: ' + caseIds);
        if(caseIds.size() > 0) {
            casesToUpdate = [SELECT Id, ParentId, Case_Time_Logged__c, Hierarchical_Time_Logged__c, (SELECT Id, Case__c, ParentLogbookId__c, Duration_Minutes__c, Billable_Time__c FROM Time_Logs__r) FROM Case WHERE Id IN :caseIds];
            for (Case cs : casesToUpdate) {
                cs.Case_Time_Logged__c = 0;
                if (cs.Hierarchical_Time_Logged__c == NULL) {
                    cs.Hierarchical_Time_Logged__c = 0;
                }
                for (Time_Log__c tl : cs.Time_Logs__r) {
                    if (tl.Billable_Time__c != NULL) {
                        cs.Case_Time_Logged__c += tl.Billable_Time__c;
                    }
                }
                
                if (cs.ParentId != NULL) {
                    parentCaseIds.add(cs.ParentId);
                }
                
            }
            system.debug('casesToUpdate: ' + casesToUpdate);
            update casesToUpdate;
        }
        
        system.debug('parentCaseIds: ' + parentCaseIds);
        if(parentCaseIds.size() > 0) {
            parentCasesToUpdate = [SELECT Id, ParentId, Hierarchical_Time_Logged__c, (SELECT Id, Case_Time_Logged__c FROM Cases) FROM Case WHERE Id IN :parentCaseIds];
            for (Case parentCase : parentCasesToUpdate) {
                parentCase.Hierarchical_Time_Logged__c = 0;
                for (Case childCase : parentCase.Cases) {
                    if (childCase.Case_Time_Logged__c != NULL) {
                        parentCase.Hierarchical_Time_Logged__c += childCase.Case_Time_Logged__c;
                    }
                }
            }
            system.debug('parentCasesToUpdate: ' + parentCasesToUpdate);
            update parentCasesToUpdate;
        }
        
        if (contactIds.size() > 0) {
            Util.recalcContacts(contactIds);
        }
        if (accountIds.size() > 0) {
            Util.recalcAccounts(accountIds);
        }
    }
}