unpackaged/main/default/objects/Case/fields/Total_Billable_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Billable_Time__c</fullName>
    <description>Roll up of all Billable Time from all Time Log records for this parent Travel Planning Logbook and all related Logbooks.</description>
    <inlineHelpText>Roll up of all Billable Time from all Time Log records for this parent Travel Planning Logbook and all related Logbooks.</inlineHelpText>
    <label>Total Billable Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>New</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Travel_Planning.recordType-meta.xml
<RecordType>
    <fullName>Travel_Planning</fullName>
    <active>true</active>
    <businessProcess>Master Support Process</businessProcess>
    <label>Travel Planning</label>
</RecordType>

unpackaged/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Time_Log__c/fields/Billable_Time__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time__c</fullName>
    <formula>VALUE(TEXT(Multiplier__c)) *  Duration_Minutes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billable Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Time_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TimeLogRollupBatch.cls
public class TimeLogRollupBatch implements Database.Batchable<sObject>, Database.Stateful {

    private Id singleCaseId;
    private String query;
    private Map<Id, Decimal> caseToTotalTimeMap;

    // Constructor for ALL Travel_Planning cases (default)
    public TimeLogRollupBatch() {
        this.query = 'SELECT Id, Total_Billable_Time__c FROM Case WHERE RecordType.DeveloperName = \'Travel_Planning\'';
        this.caseToTotalTimeMap = new Map<Id, Decimal>();
    }

    // Constructor for a single Travel_Planning Case
    public TimeLogRollupBatch(Id caseId) {
        this.singleCaseId = caseId;
        this.query = 'SELECT Id, Total_Billable_Time__c FROM Case WHERE Id = :singleCaseId AND RecordType.DeveloperName = \'Travel_Planning\'';
        this.caseToTotalTimeMap = new Map<Id, Decimal>();
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Case> scope) {
        Set<Id> caseIds = new Set<Id>();
        for (Case c : scope) {
            caseIds.add(c.Id);
        }

        // First, get all related cases (both parent and child relationships)
        Map<Id, Set<Id>> caseToRelatedCasesMap = new Map<Id, Set<Id>>();
        for (Case c : [SELECT Id, ParentId, (SELECT Id FROM Cases) FROM Case WHERE Id IN :caseIds OR ParentId IN :caseIds]) {
            if (caseIds.contains(c.Id)) {
                Set<Id> relatedCases = new Set<Id>();
                if (c.ParentId != null) {
                    relatedCases.add(c.ParentId);
                }
                for (Case childCase : c.Cases) {
                    relatedCases.add(childCase.Id);
                }
                caseToRelatedCasesMap.put(c.Id, relatedCases);
            }
        }

        // Gather all related Case Ids
        Set<Id> allRelatedCaseIds = new Set<Id>();
        for (Set<Id> relatedCases : caseToRelatedCasesMap.values()) {
            allRelatedCaseIds.addAll(relatedCases);
        }
        allRelatedCaseIds.addAll(caseIds);

        // Query all relevant Time Logs
        List<Time_Log__c> timeLogs = [
            SELECT Id, Case__c, Billable_Time__c
            FROM Time_Log__c
            WHERE Case__c IN :allRelatedCaseIds
        ];

        // Aggregate billable time
        for (Time_Log__c tl : timeLogs) {
            for (Id travelPlanningCaseId : caseToRelatedCasesMap.keySet()) {
                Set<Id> relatedCases = caseToRelatedCasesMap.get(travelPlanningCaseId);
                if (relatedCases.contains(tl.Case__c)) {
                    Decimal currentTotal = caseToTotalTimeMap.get(travelPlanningCaseId);
                    caseToTotalTimeMap.put(travelPlanningCaseId, (currentTotal != null ? currentTotal : 0) + (tl.Billable_Time__c != null ? tl.Billable_Time__c : 0));
                }
            }

            if (caseIds.contains(tl.Case__c)) {
                Decimal currentTotal = caseToTotalTimeMap.get(tl.Case__c);
                caseToTotalTimeMap.put(tl.Case__c, (currentTotal != null ? currentTotal : 0) + (tl.Billable_Time__c != null ? tl.Billable_Time__c : 0));
            }
        }

        // Update Cases
        List<Case> casesToUpdate = new List<Case>();
        for (Case c : scope) {
            if (caseToTotalTimeMap.containsKey(c.Id)) {
                c.Total_Billable_Time__c = caseToTotalTimeMap.get(c.Id);
                casesToUpdate.add(c);
            }
        }

        if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        }
    }

    public void finish(Database.BatchableContext BC) {
        // Optional post-processing
    }
}