unpackaged/main/default/objects/Contact/fields/Anniversary__c.field-meta.xml
<CustomField>
    <fullName>Anniversary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Anniversary</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reminder__c/Reminder__c.object-meta.xml
<CustomObject>
    <label>Reminder</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reminder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reminders</relationshipLabel>
    <relationshipName>Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Reminder__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reminder__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <label>Recurring</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reminder__c/fields/SyncId__c.field-meta.xml
<CustomField>
    <fullName>SyncId__c</fullName>
    <description>For syncing anniversary and birthday reminders created by the system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SyncId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reminder__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Child's Birthday</fullName>
            </value>
            <value>
                <fullName>Spouse's Birthday</fullName>
            </value>
            <value>
                <fullName>Parent's Birthday</fullName>
            </value>
            <value>
                <fullName>Client’s Birthday</fullName>
            </value>
            <value>
                <fullName>Other Birthday</fullName>
            </value>
            <value>
                <fullName>Anniversary</fullName>
            </value>
            <value>
                <fullName>Insurance Expiration</fullName>
            </value>
            <value>
                <fullName>Passport Expiration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerContact.cls
public  class TriggerHandlerContact extends TriggerHandler {    
    // Constructor 
    public TriggerHandlerContact() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert()  {
        reminderSync(Trigger.new, NULL);
    }
    public override void afterUpdate()  {
        reminderSync(Trigger.new, Trigger.oldMap);
    }
    public override void afterDelete()  {}
    public override void afterUndelete(){}
    
    private void reminderSync(List<sObject> newCons, Map<Id,sObject> oldConMap){
        system.debug('reminderSync');
        
        List<Contact> newConList = (List<Contact>) newCons;
        List<Reminder__c> upsReminderList = new List<Reminder__c>();
        List<Reminder__c> delReminderList = new List<Reminder__c>();
        
        Set<String> rmdToDel = new Set<String>();

        Map<Id,Contact> oldMap;
        if(oldConMap != NULL){
            //existing contact, sync reminders
            oldMap = (Map<Id,Contact>) oldConMap;
            
            for(Contact con : newConList){
                if (con.Anniversary__c != oldMap.get(con.Id).Anniversary__c) {
                    if (con.Anniversary__c == NULL) { //anniversary deleted
                        rmdToDel.add(con.Id + 'Anniversary');
                    } else { //anniversary changed
                        Reminder__c newReminder = new Reminder__c(
                            Name = 'Anniversary',
                            Contact__c = con.Id,
                            Date__c = con.Anniversary__c,
                            Recurring__c = 'Annually',
                            Type__c = 'Anniversary',
                            SyncId__c = con.Id + 'Anniversary'
                        );
                        upsReminderList.add(newReminder);
                    }
                }
                
                if (con.Birthdate__c != oldMap.get(con.Id).Birthdate__c) {
                    if (con.Birthdate__c == NULL) { //birthday deleted
                        rmdToDel.add(con.Id + 'Birthday');
                    } else { //birthday changed
                        Reminder__c newReminder = new Reminder__c(
                            Name = 'Birthday',
                            Contact__c = con.Id,
                            Date__c = con.Birthdate__c,
                            Recurring__c = 'Annually',
                            Type__c = 'Birthday',
                            SyncId__c = con.Id + 'Birthday'
                        );
                        upsReminderList.add(newReminder);
                    }
                }
            }
        } else {
            //new contact, create reminders
            for(Contact con : newConList){
                if (con.Anniversary__c != NULL) {
                    Reminder__c newReminder = new Reminder__c(
                        Name = 'Anniversary',
                        Contact__c = con.Id,
                        Date__c = con.Anniversary__c,
                        Recurring__c = 'Annually',
                        Type__c = 'Anniversary',
                        SyncId__c = con.Id + 'Anniversary'
                    );
                    upsReminderList.add(newReminder);
                }
                
                if (con.Birthdate__c != NULL) {
                    Reminder__c newReminder = new Reminder__c(
                        Name = 'Birthday',
                        Contact__c = con.Id,
                        Date__c = con.Birthdate__c,
                        Recurring__c = 'Annually',
                        Type__c = 'Birthday',
                        SyncId__c = con.Id + 'Birthday'
                    );
                    upsReminderList.add(newReminder);
                }
            }
        }
        
        if (!upsReminderList.isEmpty()) {
            upsert upsReminderList SyncId__c;
        }
        
        if (!rmdToDel.isEmpty()) {
            delete [SELECT Id FROM Reminder__c WHERE SyncId__c IN :rmdToDel];
        }
    }
}