unpackaged/main/default/objects/Linked_Payment_Method__c/Linked_Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Linked Payment Method</label>
    <nameField>
        <displayFormat>LPM-{0}</displayFormat>
        <label>Linked Payment Method #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method__c</fullName>
    <formula>HYPERLINK('./' + Linked_Payment_Method_From__c, Linked_Payment_Method_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('./' + Linked_Payment_Method_To__c, Linked_Payment_Method_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Payment Method</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method_From__c</fullName>
    <label>Linked Payment Method From</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Linked Payment Methods (From)</relationshipLabel>
    <relationshipName>Linked_Payment_Methods_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This payment method will initially be synced to the payment method selected here. Then they will be synced up whenever either payment method is updated.</inlineHelpText>
    <label>Linked Payment Method To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Payment_Method_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Linked Payment Methods (To)</relationshipLabel>
    <relationshipName>Linked_Payment_Methods_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment_Method__c/fields/Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Billing Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/ClientAccount__c.field-meta.xml
<CustomField>
    <fullName>ClientAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Credit_Card_Address__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Card Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Credit_Card_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Number_Encrypted__c</fullName>
    <label>Credit Card Number</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Month__c</fullName>
    <label>Expiration Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01 - January</fullName>
            </value>
            <value>
                <fullName>02 - February</fullName>
            </value>
            <value>
                <fullName>03 - March</fullName>
            </value>
            <value>
                <fullName>04 - April</fullName>
            </value>
            <value>
                <fullName>05 - May</fullName>
            </value>
            <value>
                <fullName>06 - June</fullName>
            </value>
            <value>
                <fullName>07 - July</fullName>
            </value>
            <value>
                <fullName>08 - August</fullName>
            </value>
            <value>
                <fullName>09 - September</fullName>
            </value>
            <value>
                <fullName>10 - October</fullName>
            </value>
            <value>
                <fullName>11 - November</fullName>
            </value>
            <value>
                <fullName>12 - December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Inactive_Reason__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inactive Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Last_4_Digits_Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Last_4_Digits_Credit_Card__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last 4 Digits Credit Card</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>VENMO</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Retainer_Payment__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retainer Payment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Security_Code__c.field-meta.xml
<CustomField>
    <fullName>Security_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Security Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerPaymentMethod.cls
public class TriggerHandlerPaymentMethod extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerPaymentMethod() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {
        setLast4Digits(Trigger.new);
    }
    public override void beforeUpdate() {
        setLast4Digits(Trigger.new);
    }
    public override void beforeDelete() {}
    public override void afterInsert() {}
    public override void afterUpdate()  {
        if(RecursiveTriggerHandler.runOnce()){
            syncPaymentMethods(Trigger.new);
        }
    }
    public override void afterDelete()  {}
    public override void afterUndelete() {}
    
    private void setLast4Digits(List<sObject> newPMs){
        system.debug('setLast4Digits');
        List<Payment_Method__c> newPMList = (List<Payment_Method__c>) newPMs;
        
        for(Payment_Method__c pm : newPMList){
            if (pm.Credit_Card_Number_Encrypted__c!=NULL) {
                pm.Last_4_Digits_Credit_Card__c = pm.Credit_Card_Number_Encrypted__c.right(4);
            } else {
                pm.Last_4_Digits_Credit_Card__c = NULL;
            }

        }
    }
    
    private void syncPaymentMethods(List<sObject> newPMs){
        system.debug('syncPaymentMethods');
        List<Payment_Method__c> newPMList = (List<Payment_Method__c>) newPMs;
        List<Payment_Method__c> pmToUpdate = new List<Payment_Method__c>();
        
        for(Payment_Method__c primaryPM : newPMList){
            system.debug('Sync From Addresses');
            Set<Id> linkedPMIds = new Set<Id>();
            Set<Id> pmIds = new Set<Id>();
            
            for (Linked_Payment_Method__c lpm : [SELECT Id, Linked_Payment_Method_From__r.Id, Linked_Payment_Method_To__r.Id FROM Linked_Payment_Method__c WHERE Linked_Payment_Method_From__c = :primaryPM.Id OR Linked_Payment_Method_To__c = :primaryPM.Id]) {
                linkedPMIds.add(lpm.Id);
                pmIds.add(lpm.Linked_Payment_Method_From__r.Id);
                pmIds.add(lpm.Linked_Payment_Method_To__r.Id);
            }
            
            //loop to get addresses 9 levels deep...
            Integer listSize = pmIds.size();
            for (Integer i = 0; i < 9; i++) {
                System.debug('i: ' + i);
                
                for (Linked_Payment_Method__c lpm : [SELECT Id, Linked_Payment_Method_From__r.Id, Linked_Payment_Method_To__r.Id FROM Linked_Payment_Method__c WHERE Linked_Payment_Method_From__c IN :pmIds OR Linked_Payment_Method_To__c IN :pmIds]) {
                    linkedPMIds.add(lpm.Id);
                    pmIds.add(lpm.Linked_Payment_Method_From__r.Id);
                    pmIds.add(lpm.Linked_Payment_Method_To__r.Id);
                }
                
                //if list didn't increase, means no more addresses to find so exit
                if (listSize == pmIds.size()) {
                    break;
                } else {
                    listSize = pmIds.size();
                }
            }
            
            system.debug('primaryPM: ' + primaryPM);
            
            for (Id childAddId : pmIds) {
                if (childAddId == primaryPM.Id) {
                    continue;
                } else {
                    Payment_Method__c childPM = new Payment_Method__c(Id = childAddId);
                    childPM.Active__c = primaryPM.Active__c;
                    childPM.ClientAccount__c = primaryPM.ClientAccount__c;
                    childPM.Billing_Zip_Code__c = primaryPM.Billing_Zip_Code__c;
                    childPM.Credit_Card_Address__c = primaryPM.Credit_Card_Address__c;
                    childPM.Credit_Card_Number_Encrypted__c = primaryPM.Credit_Card_Number_Encrypted__c;
                    childPM.Description__c = primaryPM.Description__c;
                    childPM.Employee__c = primaryPM.Employee__c;
                    childPM.Expiration_Month__c = primaryPM.Expiration_Month__c;
                    childPM.Expiration_Year__c = primaryPM.Expiration_Year__c;
                    childPM.Inactive_Reason__c = primaryPM.Inactive_Reason__c;
                    childPM.Primary__c = primaryPM.Primary__c;
                    childPM.Retainer_Payment__c = primaryPM.Retainer_Payment__c;
                    childPM.Security_Code__c = primaryPM.Security_Code__c;
                    childPM.Type__c = primaryPM.Type__c;
                    childPM.Payment_Type__c = primaryPM.Payment_Type__c;
                    pmToUpdate.add(childPM); 
                }
            }
        }
        
        if (!pmToUpdate.isEmpty()) {
            system.debug('pmToUpdate: ' + pmToUpdate);
            system.debug('pmToUpdate.size(): ' + pmToUpdate.size());
            update pmToUpdate;
        }
    }
}