unpackaged/main/default/objects/Linked_Payment_Method__c/Linked_Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Linked Payment Method</label>
    <nameField>
        <displayFormat>LPM-{0}</displayFormat>
        <label>Linked Payment Method #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Link_Payment_Method_To__c.field-meta.xml
<CustomField>
    <fullName>Link_Payment_Method_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is just used to initially do the cloning</description>
    <label>Link Payment Method To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked Payment Methods</relationshipLabel>
    <relationshipName>Linked_Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method__c</fullName>
    <formula>HYPERLINK('./' + Linked_Payment_Method_From__c, Linked_Payment_Method_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('./' + Linked_Payment_Method_To__c, Linked_Payment_Method_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Payment Method</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method_From__c</fullName>
    <label>Linked Payment Method From</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Linked Payment Methods (From)</relationshipLabel>
    <relationshipName>Linked_Payment_Methods_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Payment_Method__c/fields/Linked_Payment_Method_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Payment_Method_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This payment method will initially be synced to the payment method selected here. Then they will be synced up whenever either payment method is updated.</inlineHelpText>
    <label>Linked Payment Method To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Payment_Method_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Linked Payment Methods (To)</relationshipLabel>
    <relationshipName>Linked_Payment_Methods_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment_Method__c/fields/Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Billing Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/ClientAccount__c.field-meta.xml
<CustomField>
    <fullName>ClientAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Credit_Card_Address__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Card Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Credit_Card_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Number_Encrypted__c</fullName>
    <label>Credit Card Number</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Month__c</fullName>
    <label>Expiration Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01 - January</fullName>
            </value>
            <value>
                <fullName>02 - February</fullName>
            </value>
            <value>
                <fullName>03 - March</fullName>
            </value>
            <value>
                <fullName>04 - April</fullName>
            </value>
            <value>
                <fullName>05 - May</fullName>
            </value>
            <value>
                <fullName>06 - June</fullName>
            </value>
            <value>
                <fullName>07 - July</fullName>
            </value>
            <value>
                <fullName>08 - August</fullName>
            </value>
            <value>
                <fullName>09 - September</fullName>
            </value>
            <value>
                <fullName>10 - October</fullName>
            </value>
            <value>
                <fullName>11 - November</fullName>
            </value>
            <value>
                <fullName>12 - December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Inactive_Reason__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inactive Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Last_4_Digits_Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Last_4_Digits_Credit_Card__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last 4 Digits Credit Card</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>VENMO</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Retainer_Payment__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retainer Payment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Security_Code__c.field-meta.xml
<CustomField>
    <fullName>Security_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Security Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerLinkedPaymentMethod.cls
public  class TriggerHandlerLinkedPaymentMethod extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerLinkedPaymentMethod() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {
        if(RecursiveTriggerHandler.runOnce()){
            beforeLogic(Trigger.new);
        }
    }
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert() {}
    public override void afterUpdate()  {}
    public override void afterDelete()  {}
    public override void afterUndelete() {}
    
    private void beforeLogic(List<sObject> newLinkedPMs){
        system.debug('beforeLogic');
        List<Linked_Payment_Method__c> newLinkedPMList = (List<Linked_Payment_Method__c>) newLinkedPMs;
        List<Payment_Method__c> pmToCreate = new List<Payment_Method__c>();
       
        for(Linked_Payment_Method__c linkedPM : newLinkedPMList){
            system.debug('linkedPM1: ' + linkedPM);
            
            //create new payment method logic
            if (linkedPM.Link_Payment_Method_To__c != NULL) {
                for (Payment_Method__c fromPM : [SELECT Active__c,Billing_Zip_Code__c,ClientAccount__c,Client__c,Credit_Card_Address__c,Credit_Card_Number_Encrypted__c,Description__c,Employee__c,Expiration_Month__c,Expiration_Year__c,Id,Inactive_Reason__c,Last_4_Digits_Credit_Card__c,Primary__c,Retainer_Payment__c,Security_Code__c,Type__c,Payment_Type__c 
                                                 FROM Payment_Method__c
                                                 WHERE Id = :linkedPM.Linked_Payment_Method_From__c LIMIT 1]) {
                                                     Payment_Method__c newPM = new Payment_Method__c();
                                                     newPM.Client__c = linkedPM.Link_Payment_Method_To__c;
                                                     newPM.ClientAccount__c = fromPM.ClientAccount__c;
                                                     newPM.Active__c = fromPM.Active__c;
                                                     newPM.Billing_Zip_Code__c = fromPM.Billing_Zip_Code__c;
                                                     newPM.Credit_Card_Address__c = fromPM.Credit_Card_Address__c;
                                                     newPM.Credit_Card_Number_Encrypted__c = fromPM.Credit_Card_Number_Encrypted__c;
                                                     newPM.Description__c = fromPM.Description__c;
                                                     newPM.Employee__c = fromPM.Employee__c;
                                                     newPM.Expiration_Month__c = fromPM.Expiration_Month__c;
                                                     newPM.Expiration_Year__c = fromPM.Expiration_Year__c;
                                                     newPM.Inactive_Reason__c = fromPM.Inactive_Reason__c;
                                                     newPM.Primary__c = fromPM.Primary__c;
                                                     newPM.Retainer_Payment__c = fromPM.Retainer_Payment__c;
                                                     newPM.Security_Code__c = fromPM.Security_Code__c;
                                                     newPM.Type__c = fromPM.Type__c;
                                                     newPM.Payment_Type__c = fromPM.Payment_Type__c;
                                                     insert newPM; 
                                                     system.debug('newPM: ' + newPM);
                                                     linkedPM.Linked_Payment_Method_To__c = newPM.Id;
                                                     system.debug('newPM2: ' + newPM);
                                                 }
            } else if (linkedPM.Linked_Payment_Method_To__c != NULL) { //link to existing pm logic so sync
                for (Payment_Method__c fromPM : [SELECT Active__c,Billing_Zip_Code__c,ClientAccount__c,Client__c,Credit_Card_Address__c,Credit_Card_Number_Encrypted__c,Description__c,Employee__c,Expiration_Month__c,Expiration_Year__c,Id,Inactive_Reason__c,Last_4_Digits_Credit_Card__c,Primary__c,Retainer_Payment__c,Security_Code__c,Type__c,Payment_Type__c
                                                 FROM Payment_Method__c
                                                 WHERE Id = :linkedPM.Linked_Payment_Method_From__c LIMIT 1]) {
                                                     Payment_Method__c syncPM = new Payment_Method__c(Id = linkedPM.Linked_Payment_Method_To__c);
                                                     syncPM.Active__c = fromPM.Active__c;
                                                     syncPM.Billing_Zip_Code__c = fromPM.Billing_Zip_Code__c;
                                                     syncPM.Credit_Card_Address__c = fromPM.Credit_Card_Address__c;
                                                     syncPM.Credit_Card_Number_Encrypted__c = fromPM.Credit_Card_Number_Encrypted__c;
                                                     syncPM.Description__c = fromPM.Description__c;
                                                     syncPM.Employee__c = fromPM.Employee__c;
                                                     syncPM.Expiration_Month__c = fromPM.Expiration_Month__c;
                                                     syncPM.Expiration_Year__c = fromPM.Expiration_Year__c;
                                                     syncPM.Inactive_Reason__c = fromPM.Inactive_Reason__c;
                                                     syncPM.Primary__c = fromPM.Primary__c;
                                                     syncPM.Retainer_Payment__c = fromPM.Retainer_Payment__c;
                                                     syncPM.Security_Code__c = fromPM.Security_Code__c;
                                                     syncPM.Type__c = fromPM.Type__c;
                                                     syncPM.Payment_Type__c = fromPM.Payment_Type__c;
                                                     RecursiveTriggerHandler.isFirstTime = TRUE;
                                                     update syncPM; 
                                                     system.debug('syncPM: ' + syncPM);
                                                 }
            }
        }
    }
}