unpackaged/main/default/objects/Hates__c/Hates__c.object-meta.xml
<CustomObject>
    <label>Hate</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Hates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hates__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Airline_Seat_Hate__c.field-meta.xml
<CustomField>
    <fullName>Airline_Seat_Hate__c</fullName>
    <label>Airline Seat Hate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Aisle</fullName>
            </value>
            <value>
                <fullName>Window</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Avid_Wine_Collector__c.field-meta.xml
<CustomField>
    <fullName>Avid_Wine_Collector__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Avid Wine Collector</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Gym__c.field-meta.xml
<CustomField>
    <fullName>Gym__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gym</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Hates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated__c.field-meta.xml
<CustomField>
    <fullName>Hated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated_Means_of_Air_Travel__c.field-meta.xml
<CustomField>
    <fullName>Hated_Means_of_Air_Travel__c</fullName>
    <label>Hated Means of Air Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated_Seating_Class__c.field-meta.xml
<CustomField>
    <fullName>Hated_Seating_Class__c</fullName>
    <label>Hated Seating Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy Plus</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Member_of_Social_or_Athletic_Club__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Social_or_Athletic_Club__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Member of Social or Athletic Club</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Notes_Summary__c.field-meta.xml
<CustomField>
    <fullName>Notes_Summary__c</fullName>
    <description>This is a summary field for notes. Set via WF rule.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Room_Hate__c.field-meta.xml
<CustomField>
    <fullName>Room_Hate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Hate</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Security_Q_A__c.field-meta.xml
<CustomField>
    <fullName>Security_Q_A__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Security Q&amp;A</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Sports_Played__c.field-meta.xml
<CustomField>
    <fullName>Sports_Played__c</fullName>
    <label>Sports Played</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abseiling</fullName>
            </value>
            <value>
                <fullName>Aerobics</fullName>
            </value>
            <value>
                <fullName>Aikido</fullName>
            </value>
            <value>
                <fullName>Archery</fullName>
            </value>
            <value>
                <fullName>Artistic gymnastics</fullName>
            </value>
            <value>
                <fullName>Badminton</fullName>
            </value>
            <value>
                <fullName>BASE jumping</fullName>
            </value>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Basketball</fullName>
            </value>
            <value>
                <fullName>Baton twirling</fullName>
            </value>
            <value>
                <fullName>Bobsleigh</fullName>
            </value>
            <value>
                <fullName>Bodyboarding</fullName>
            </value>
            <value>
                <fullName>Bodybuilding</fullName>
            </value>
            <value>
                <fullName>Bouldering</fullName>
            </value>
            <value>
                <fullName>Bowling</fullName>
            </value>
            <value>
                <fullName>Boxing</fullName>
            </value>
            <value>
                <fullName>Canoeing</fullName>
            </value>
            <value>
                <fullName>Climbing</fullName>
            </value>
            <value>
                <fullName>Cricket</fullName>
            </value>
            <value>
                <fullName>Cross-country cycling</fullName>
            </value>
            <value>
                <fullName>Cross-country equestrianism</fullName>
            </value>
            <value>
                <fullName>Cross-country running</fullName>
            </value>
            <value>
                <fullName>Cross-country skiing</fullName>
            </value>
            <value>
                <fullName>Curling</fullName>
            </value>
            <value>
                <fullName>Cycling</fullName>
            </value>
            <value>
                <fullName>Discus throw</fullName>
            </value>
            <value>
                <fullName>Diving</fullName>
            </value>
            <value>
                <fullName>Dodgeball</fullName>
            </value>
            <value>
                <fullName>Equestrianism</fullName>
            </value>
            <value>
                <fullName>Fencing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Suggested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Avoid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amarone</fullName>
            </value>
            <value>
                <fullName>Barbaresco</fullName>
            </value>
            <value>
                <fullName>Barlool</fullName>
            </value>
            <value>
                <fullName>Barolo</fullName>
            </value>
            <value>
                <fullName>Beaujolais</fullName>
            </value>
            <value>
                <fullName>Beaujolais Nouveau</fullName>
            </value>
            <value>
                <fullName>Bordeaux</fullName>
            </value>
            <value>
                <fullName>Bourbon</fullName>
            </value>
            <value>
                <fullName>Burgundy</fullName>
            </value>
            <value>
                <fullName>Cabernet Franc</fullName>
            </value>
            <value>
                <fullName>Cabernet Sauvignon</fullName>
            </value>
            <value>
                <fullName>Champagne</fullName>
            </value>
            <value>
                <fullName>Chardonnay</fullName>
            </value>
            <value>
                <fullName>Chenin Blanc</fullName>
            </value>
            <value>
                <fullName>Chianti</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Cognac</fullName>
            </value>
            <value>
                <fullName>Falanghina</fullName>
            </value>
            <value>
                <fullName>Gamay</fullName>
            </value>
            <value>
                <fullName>Gewurtztraminer</fullName>
            </value>
            <value>
                <fullName>Gin</fullName>
            </value>
            <value>
                <fullName>Grenache</fullName>
            </value>
            <value>
                <fullName>Gruner</fullName>
            </value>
            <value>
                <fullName>Ice Wine</fullName>
            </value>
            <value>
                <fullName>Malbec</fullName>
            </value>
            <value>
                <fullName>Merlot</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Mezcal</fullName>
            </value>
            <value>
                <fullName>Moschofilero</fullName>
            </value>
            <value>
                <fullName>Nebbiolo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gym</fullName>
            </value>
            <value>
                <fullName>Venue for Facials</fullName>
            </value>
            <value>
                <fullName>Venue for Haircuts</fullName>
            </value>
            <value>
                <fullName>Venue for Massages</fullName>
            </value>
            <value>
                <fullName>Dermatologist</fullName>
            </value>
            <value>
                <fullName>Personal Trainer</fullName>
            </value>
            <value>
                <fullName>PT/Acupuncture</fullName>
            </value>
            <value>
                <fullName>Nutritionist</fullName>
            </value>
            <value>
                <fullName>Studio/Class</fullName>
            </value>
            <value>
                <fullName>Favorite Restaurant</fullName>
            </value>
            <value>
                <fullName>Business Dinner</fullName>
            </value>
            <value>
                <fullName>Business Lunch</fullName>
            </value>
            <value>
                <fullName>Business Breakfast</fullName>
            </value>
            <value>
                <fullName>Special Occasion</fullName>
            </value>
            <value>
                <fullName>Weekend Brunch</fullName>
            </value>
            <value>
                <fullName>Cuisine</fullName>
            </value>
            <value>
                <fullName>Quiet Dinner</fullName>
            </value>
            <value>
                <fullName>Restaurant Investor In</fullName>
            </value>
            <value>
                <fullName>Restaurant Client Doesn't Like</fullName>
            </value>
            <value>
                <fullName>Trendy/Fun Scene</fullName>
            </value>
            <value>
                <fullName>Favorite Clothing Brand</fullName>
            </value>
            <value>
                <fullName>Interests/Hobbies</fullName>
            </value>
            <value>
                <fullName>Cocktail</fullName>
            </value>
            <value>
                <fullName>Wine - RED</fullName>
            </value>
            <value>
                <fullName>Wine - WHITE</fullName>
            </value>
            <value>
                <fullName>Wine - other</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/Linked_Hate__c.object-meta.xml
<CustomObject>
    <label>Linked Hate</label>
    <nameField>
        <displayFormat>LH-{0}</displayFormat>
        <label>Linked Hate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Hates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Hate__c/fields/Link_Hate_To__c.field-meta.xml
<CustomField>
    <fullName>Link_Hate_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link Hate To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked Hates</relationshipLabel>
    <relationshipName>Linked_Hates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate__c</fullName>
    <formula>HYPERLINK('/' + Linked_Hate_From__c, Linked_Hate_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Hate_To__c, Linked_Hate_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Hate</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerLinkedHate.cls
public  class TriggerHandlerLinkedHate extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerLinkedHate() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {
        if(RecursiveTriggerHandler.runOnce()){
            beforeLogic(Trigger.new);
        }
    }
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert() {}
    public override void afterUpdate() {}
    public override void afterDelete() {}
    public override void afterUndelete() {}
    
    private void beforeLogic(List<sObject> newLinkedHates){
        system.debug('beforeLogic');
        List<Linked_Hate__c> newLinkedHateList = (List<Linked_Hate__c>) newLinkedHates;
        
        for(Linked_Hate__c linkedH : newLinkedHateList){
            system.debug('linkedH1: ' + linkedH);
            
            //Create new general preference logic
            if (linkedH.Link_Hate_To__c != NULL) {
                for (Hates__c fromH : [SELECT Id,Account_Number__c,Airline_Seat_Hate__c,Avid_Wine_Collector__c,Gym__c,Hated__c,Hated_Means_of_Air_Travel__c,Hated_Seating_Class__c,
                                       Member_of_Social_or_Athletic_Club__c,Notes_Summary__c,Notes__c,Password__c,RecordTypeId,Repeat_Orders__c,Room_Hate__c,Season_Ticket_Holder__c,
                                       Security_Q_A__c,Sports_Played__c,Status__c,Sub_Type__c,Support_Line__c,Type__c,Username__c,Vacation_Locale_Hate__c,Hated_Vendor__c,Website__c,
                                       Wine_Cellar__c
                                       FROM Hates__c 
                                       WHERE Id = :linkedH.Linked_Hate_From__c LIMIT 1]) {
                                           Hates__c newH = new Hates__c();
                                           newH.Contact_Name__c = linkedH.Link_Hate_To__c;
                                           newH.Account_Number__c = fromH.Account_Number__c;
                                           newH.Airline_Seat_Hate__c = fromH.Airline_Seat_Hate__c;
                                           newH.Avid_Wine_Collector__c = fromH.Avid_Wine_Collector__c;
                                           newH.Gym__c = fromH.Gym__c;
                                           newH.Hated__c = fromH.Hated__c;
                                           newH.Hated_Means_of_Air_Travel__c = fromH.Hated_Means_of_Air_Travel__c;
                                           newH.Hated_Seating_Class__c = fromH.Hated_Seating_Class__c;
                                           newH.Member_of_Social_or_Athletic_Club__c = fromH.Member_of_Social_or_Athletic_Club__c;
                                           newH.Notes_Summary__c = fromH.Notes_Summary__c;
                                           newH.Notes__c = fromH.Notes__c;
                                           newH.Password__c = fromH.Password__c;
                                           newH.RecordTypeId = fromH.RecordTypeId;
                                           newH.Repeat_Orders__c = fromH.Repeat_Orders__c;
                                           newH.Room_Hate__c = fromH.Room_Hate__c;
                                           newH.Season_Ticket_Holder__c = fromH.Season_Ticket_Holder__c;
                                           newH.Security_Q_A__c = fromH.Security_Q_A__c;
                                           newH.Sports_Played__c = fromH.Sports_Played__c;
                                           newH.Status__c = fromH.Status__c;
                                           newH.Sub_Type__c = fromH.Sub_Type__c;
                                           newH.Support_Line__c = fromH.Support_Line__c;
                                           newH.Type__c = fromH.Type__c;
                                           newH.Username__c = fromH.Username__c;
                                           newH.Vacation_Locale_Hate__c = fromH.Vacation_Locale_Hate__c;
                                           newH.Hated_Vendor__c = fromH.Hated_Vendor__c;
                                           newH.Website__c = fromH.Website__c;
                                           newH.Wine_Cellar__c = fromH.Wine_Cellar__c;
                                           insert newH; 
                                           system.debug('newH: ' + newH);
                                           linkedH.Linked_Hate_To__c = newH.Id;
                                           system.debug('newH2: ' + newH);
                                       }
            } else if (linkedH.Linked_Hate_To__c != NULL) { //link to existing general preference logic so sync
                for (Hates__c fromH : [SELECT Id,Account_Number__c,Airline_Seat_Hate__c,Avid_Wine_Collector__c,Gym__c,Hated__c,Hated_Means_of_Air_Travel__c,Hated_Seating_Class__c,
                                       Member_of_Social_or_Athletic_Club__c,Notes_Summary__c,Notes__c,Password__c,RecordTypeId,Repeat_Orders__c,Room_Hate__c,Season_Ticket_Holder__c,
                                       Security_Q_A__c,Sports_Played__c,Status__c,Sub_Type__c,Support_Line__c,Type__c,Username__c,Vacation_Locale_Hate__c,Hated_Vendor__c,Website__c,
                                       Wine_Cellar__c
                                       FROM Hates__c 
                                       WHERE Id = :linkedH.Linked_Hate_From__c LIMIT 1]) {
                                           Hates__c syncH = new Hates__c(Id = linkedH.Linked_Hate_To__c);
                                           syncH.Account_Number__c = fromH.Account_Number__c;
                                           syncH.Airline_Seat_Hate__c = fromH.Airline_Seat_Hate__c;
                                           syncH.Avid_Wine_Collector__c = fromH.Avid_Wine_Collector__c;
                                           syncH.Gym__c = fromH.Gym__c;
                                           syncH.Hated__c = fromH.Hated__c;
                                           syncH.Hated_Means_of_Air_Travel__c = fromH.Hated_Means_of_Air_Travel__c;
                                           syncH.Hated_Seating_Class__c = fromH.Hated_Seating_Class__c;
                                           syncH.Member_of_Social_or_Athletic_Club__c = fromH.Member_of_Social_or_Athletic_Club__c;
                                           syncH.Notes_Summary__c = fromH.Notes_Summary__c;
                                           syncH.Notes__c = fromH.Notes__c;
                                           syncH.Password__c = fromH.Password__c;
                                           syncH.RecordTypeId = fromH.RecordTypeId;
                                           syncH.Repeat_Orders__c = fromH.Repeat_Orders__c;
                                           syncH.Room_Hate__c = fromH.Room_Hate__c;
                                           syncH.Season_Ticket_Holder__c = fromH.Season_Ticket_Holder__c;
                                           syncH.Security_Q_A__c = fromH.Security_Q_A__c;
                                           syncH.Sports_Played__c = fromH.Sports_Played__c;
                                           syncH.Status__c = fromH.Status__c;
                                           syncH.Sub_Type__c = fromH.Sub_Type__c;
                                           syncH.Support_Line__c = fromH.Support_Line__c;
                                           syncH.Type__c = fromH.Type__c;
                                           syncH.Username__c = fromH.Username__c;
                                           syncH.Vacation_Locale_Hate__c = fromH.Vacation_Locale_Hate__c;
                                           syncH.Hated_Vendor__c = fromH.Hated_Vendor__c;
                                           syncH.Website__c = fromH.Website__c;
                                           syncH.Wine_Cellar__c = fromH.Wine_Cellar__c;
                                           RecursiveTriggerHandler.isFirstTime = TRUE;
                                           update syncH; 
                                           system.debug('syncH: ' + syncH);
                                       }
            }
        }
    }
}