unpackaged/main/default/objects/Hates__c/Hates__c.object-meta.xml
<CustomObject>
    <label>Hate</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Hates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hates__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Airline_Seat_Hate__c.field-meta.xml
<CustomField>
    <fullName>Airline_Seat_Hate__c</fullName>
    <label>Airline Seat Hate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Aisle</fullName>
            </value>
            <value>
                <fullName>Window</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Avid_Wine_Collector__c.field-meta.xml
<CustomField>
    <fullName>Avid_Wine_Collector__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Avid Wine Collector</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Gym__c.field-meta.xml
<CustomField>
    <fullName>Gym__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gym</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Hates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated__c.field-meta.xml
<CustomField>
    <fullName>Hated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated_Means_of_Air_Travel__c.field-meta.xml
<CustomField>
    <fullName>Hated_Means_of_Air_Travel__c</fullName>
    <label>Hated Means of Air Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Hated_Seating_Class__c.field-meta.xml
<CustomField>
    <fullName>Hated_Seating_Class__c</fullName>
    <label>Hated Seating Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy Plus</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Member_of_Social_or_Athletic_Club__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Social_or_Athletic_Club__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Member of Social or Athletic Club</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Notes_Summary__c.field-meta.xml
<CustomField>
    <fullName>Notes_Summary__c</fullName>
    <description>This is a summary field for notes. Set via WF rule.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Room_Hate__c.field-meta.xml
<CustomField>
    <fullName>Room_Hate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Room Hate</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Security_Q_A__c.field-meta.xml
<CustomField>
    <fullName>Security_Q_A__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Security Q&amp;A</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Sports_Played__c.field-meta.xml
<CustomField>
    <fullName>Sports_Played__c</fullName>
    <label>Sports Played</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abseiling</fullName>
            </value>
            <value>
                <fullName>Aerobics</fullName>
            </value>
            <value>
                <fullName>Aikido</fullName>
            </value>
            <value>
                <fullName>Archery</fullName>
            </value>
            <value>
                <fullName>Artistic gymnastics</fullName>
            </value>
            <value>
                <fullName>Badminton</fullName>
            </value>
            <value>
                <fullName>BASE jumping</fullName>
            </value>
            <value>
                <fullName>Baseball</fullName>
            </value>
            <value>
                <fullName>Basketball</fullName>
            </value>
            <value>
                <fullName>Baton twirling</fullName>
            </value>
            <value>
                <fullName>Bobsleigh</fullName>
            </value>
            <value>
                <fullName>Bodyboarding</fullName>
            </value>
            <value>
                <fullName>Bodybuilding</fullName>
            </value>
            <value>
                <fullName>Bouldering</fullName>
            </value>
            <value>
                <fullName>Bowling</fullName>
            </value>
            <value>
                <fullName>Boxing</fullName>
            </value>
            <value>
                <fullName>Canoeing</fullName>
            </value>
            <value>
                <fullName>Climbing</fullName>
            </value>
            <value>
                <fullName>Cricket</fullName>
            </value>
            <value>
                <fullName>Cross-country cycling</fullName>
            </value>
            <value>
                <fullName>Cross-country equestrianism</fullName>
            </value>
            <value>
                <fullName>Cross-country running</fullName>
            </value>
            <value>
                <fullName>Cross-country skiing</fullName>
            </value>
            <value>
                <fullName>Curling</fullName>
            </value>
            <value>
                <fullName>Cycling</fullName>
            </value>
            <value>
                <fullName>Discus throw</fullName>
            </value>
            <value>
                <fullName>Diving</fullName>
            </value>
            <value>
                <fullName>Dodgeball</fullName>
            </value>
            <value>
                <fullName>Equestrianism</fullName>
            </value>
            <value>
                <fullName>Fencing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Suggested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Avoid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hates__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amarone</fullName>
            </value>
            <value>
                <fullName>Barbaresco</fullName>
            </value>
            <value>
                <fullName>Barlool</fullName>
            </value>
            <value>
                <fullName>Barolo</fullName>
            </value>
            <value>
                <fullName>Beaujolais</fullName>
            </value>
            <value>
                <fullName>Beaujolais Nouveau</fullName>
            </value>
            <value>
                <fullName>Bordeaux</fullName>
            </value>
            <value>
                <fullName>Bourbon</fullName>
            </value>
            <value>
                <fullName>Burgundy</fullName>
            </value>
            <value>
                <fullName>Cabernet Franc</fullName>
            </value>
            <value>
                <fullName>Cabernet Sauvignon</fullName>
            </value>
            <value>
                <fullName>Champagne</fullName>
            </value>
            <value>
                <fullName>Chardonnay</fullName>
            </value>
            <value>
                <fullName>Chenin Blanc</fullName>
            </value>
            <value>
                <fullName>Chianti</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Cognac</fullName>
            </value>
            <value>
                <fullName>Falanghina</fullName>
            </value>
            <value>
                <fullName>Gamay</fullName>
            </value>
            <value>
                <fullName>Gewurtztraminer</fullName>
            </value>
            <value>
                <fullName>Gin</fullName>
            </value>
            <value>
                <fullName>Grenache</fullName>
            </value>
            <value>
                <fullName>Gruner</fullName>
            </value>
            <value>
                <fullName>Ice Wine</fullName>
            </value>
            <value>
                <fullName>Malbec</fullName>
            </value>
            <value>
                <fullName>Merlot</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>Mezcal</fullName>
            </value>
            <value>
                <fullName>Moschofilero</fullName>
            </value>
            <value>
                <fullName>Nebbiolo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/Linked_Hate__c.object-meta.xml
<CustomObject>
    <label>Linked Hate</label>
    <nameField>
        <displayFormat>LH-{0}</displayFormat>
        <label>Linked Hate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Hates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate__c</fullName>
    <formula>HYPERLINK('/' + Linked_Hate_From__c, Linked_Hate_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Hate_To__c, Linked_Hate_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Hate</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate_From__c</fullName>
    <label>Linked Hate From</label>
    <referenceTo>Hates__c</referenceTo>
    <relationshipLabel>Linked Hates (From)</relationshipLabel>
    <relationshipName>Linked_Hates_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Hate__c/fields/Linked_Hate_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Hate_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Linked Hate To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Hate_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hates__c</referenceTo>
    <relationshipLabel>Linked Hates (Linked Hate To)</relationshipLabel>
    <relationshipName>Linked_Hates_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerHate.cls
public  class TriggerHandlerHate extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerHate() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert()  {}
    public override void afterUpdate()  {
        if(RecursiveTriggerHandler.runOnce()){
            syncHates(Trigger.new);
        }
    }
    public override void afterDelete()  {
    }
    public override void afterUndelete(){
    }
    
    private void syncHates(List<sObject> newHates){
        system.debug('syncHates');
        List<Hates__c> newHateList = (List<Hates__c>) newHates;
        List<Hates__c> hatesToUpdate = new List<Hates__c>();
                
        for(Hates__c primaryHate : newHateList){
            system.debug('Sync From Hates');
            Set<Id> linkedHateIds = new Set<Id>();
            Set<Id> hateIds = new Set<Id>();
            
            for (Linked_Hate__c lh : [SELECT Id, Linked_Hate_From__r.Id, Linked_Hate_To__r.Id FROM Linked_Hate__c WHERE Linked_Hate_From__c = :primaryHate.Id OR Linked_Hate_To__c = :primaryHate.Id]) {
                linkedHateIds.add(lh.Id);
                hateIds.add(lh.Linked_Hate_From__r.Id);
                hateIds.add(lh.Linked_Hate_To__r.Id);
            }
            
            //loop to get hates 9 levels deep...
            Integer listSize = hateIds.size();
            for (Integer i = 0; i < 9; i++) {
                System.debug('i: ' + i);
                
                for (Linked_Hate__c lh : [SELECT Id, Linked_Hate_From__r.Id, Linked_Hate_To__r.Id FROM Linked_Hate__c WHERE Linked_Hate_From__c IN :hateIds OR Linked_Hate_To__c IN :hateIds]) {
                    linkedHateIds.add(lh.Id);
                    hateIds.add(lh.Linked_Hate_From__r.Id);
                    hateIds.add(lh.Linked_Hate_To__r.Id);
                }
                
                //if list didn't increase, means no more hates to find so exit
                if (listSize == hateIds.size()) {
                    break;
                } else {
                    listSize = hateIds.size();
                }
            }
            
            system.debug('primaryHate: ' + primaryHate);
            
            for (Id childHId : hateIds) {
                if (childHId == primaryHate.Id) {
                    continue;
                } else {
                    Hates__c childHate = new Hates__c(Id = childHId);
                    childHate.Account_Number__c = primaryHate.Account_Number__c;
                    childHate.Airline_Seat_Hate__c = primaryHate.Airline_Seat_Hate__c;
                    childHate.Avid_Wine_Collector__c = primaryHate.Avid_Wine_Collector__c;
                    childHate.Gym__c = primaryHate.Gym__c;
                    childHate.Hated__c = primaryHate.Hated__c;
                    childHate.Hated_Means_of_Air_Travel__c = primaryHate.Hated_Means_of_Air_Travel__c;
                    childHate.Hated_Seating_Class__c = primaryHate.Hated_Seating_Class__c;
                    childHate.Member_of_Social_or_Athletic_Club__c = primaryHate.Member_of_Social_or_Athletic_Club__c;
                    childHate.Notes_Summary__c = primaryHate.Notes_Summary__c;
                    childHate.Notes__c = primaryHate.Notes__c;
                    childHate.Password__c = primaryHate.Password__c;
                    childHate.RecordTypeId = primaryHate.RecordTypeId;
                    childHate.Repeat_Orders__c = primaryHate.Repeat_Orders__c;
                    childHate.Room_Hate__c = primaryHate.Room_Hate__c;
                    childHate.Season_Ticket_Holder__c = primaryHate.Season_Ticket_Holder__c;
                    childHate.Security_Q_A__c = primaryHate.Security_Q_A__c;
                    childHate.Sports_Played__c = primaryHate.Sports_Played__c;
                    childHate.Status__c = primaryHate.Status__c;
                    childHate.Sub_Type__c = primaryHate.Sub_Type__c;
                    childHate.Support_Line__c = primaryHate.Support_Line__c;
                    childHate.Type__c = primaryHate.Type__c;
                    childHate.Username__c = primaryHate.Username__c;
                    childHate.Vacation_Locale_Hate__c = primaryHate.Vacation_Locale_Hate__c;
                    childHate.Hated_Vendor__c = primaryHate.Hated_Vendor__c;
                    childHate.Website__c = primaryHate.Website__c;
                    childHate.Wine_Cellar__c = primaryHate.Wine_Cellar__c;
                    hatesToUpdate.add(childHate); 
                }
            }
        }
        
        if (!hatesToUpdate.isEmpty()) {
            system.debug('hatesToUpdate: ' + hatesToUpdate);
            system.debug('hatesToUpdate.size(): ' + hatesToUpdate.size());
            update hatesToUpdate;
        }
    }
}