unpackaged/main/default/objects/Airline_Ticket__c/Airline_Ticket__c.object-meta.xml
<CustomObject>
    <label>Airline Ticket</label>
    <nameField>
        <displayFormat>PASS-{0000}</displayFormat>
        <label>Passenger ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airline Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Airline_Ticket__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Airline Tickets</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Airline_Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Airline_Ticket__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>IF(!ISBLANK(Passport__c),

Passport__r.Full_Legal_Name__c,

Contact__r.Name_as_it_appears_on_passport__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/flightBookingData.cls
public class flightBookingData {
    public String csID {get;set;}
    public String passengerNames {get{
        Set<Id> contactsSet = new Set<Id>();
        passengerNames = '';
        for (Airline_Ticket__c at : [select Id, Contact__c, Contact_Name__c From Airline_Ticket__c where Case__c =: csId Order By Contact_Name__c]) {
            if (!contactsSet.contains(at.Contact__c)) {
                if (passengerNames == '') {
                     passengerNames = at.Contact_Name__c;

                } else {
                     passengerNames = passengerNames + ', ' + at.Contact_Name__c;
                }
               
                contactsSet.add(at.Contact__c);
            }
        }
        
        return passengerNames; 
        
    }
        private set;}
}