unpackaged/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Address_Country__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Country</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Address_Street__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Address_Zip_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Zip Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Cross_Streets__c.field-meta.xml
<CustomField>
    <fullName>Cross_Streets__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cross Streets</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Doorman__c.field-meta.xml
<CustomField>
    <fullName>Doorman__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Doorman</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Facility_Manager__c.field-meta.xml
<CustomField>
    <fullName>Facility_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses (Facility Manager)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Neighbourhood__c.field-meta.xml
<CustomField>
    <fullName>Neighbourhood__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Neighbourhood</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Vacation Home</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
                <isActive>false</isActive>
                <label>Cottage</label>
            </value>
            <value>
                <fullName>Family Home</fullName>
                <isActive>false</isActive>
                <label>Family Home</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/Linked_Address__c.object-meta.xml
<CustomObject>
    <label>Linked Address</label>
    <nameField>
        <displayFormat>LA-{0}</displayFormat>
        <label>Linked Addresse #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address__c</fullName>
    <formula>HYPERLINK('/' + Linked_Address_From__c, Linked_Address_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Address_To__c, Linked_Address_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_From__c</fullName>
    <label>Linked Address From</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses (From)</relationshipLabel>
    <relationshipName>Linked_Addresses_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This address will initially be synced to the address selected here. Then they will be synced up whenever either address is updated.</inlineHelpText>
    <label>Linked Address To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Address_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses</relationshipLabel>
    <relationshipName>Linked_Addresses_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerAddress.cls
public  class TriggerHandlerAddress extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerAddress() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {}
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert()  {}
    public override void afterUpdate()  {
        if(RecursiveTriggerHandler.runOnce()){
            syncAddresses(Trigger.new);
        }
    }
    public override void afterDelete()  {
    }
    public override void afterUndelete(){
    }
    
    private void syncAddresses(List<sObject> newAddresses){
        system.debug('syncAddresses');
        List<Address__c> newAddressList = (List<Address__c>) newAddresses;
        List<Address__c> addressesToUpdate = new List<Address__c>();
                
        for(Address__c primaryAddress : newAddressList){
            system.debug('Sync From Addresses');
            Set<Id> linkedAddressIds = new Set<Id>();
            Set<Id> addressIds = new Set<Id>();
            
            for (Linked_Address__c la : [SELECT Id, Linked_Address_From__r.Id, Linked_Address_To__r.Id FROM Linked_Address__c WHERE Linked_Address_From__c = :primaryAddress.Id OR Linked_Address_To__c = :primaryAddress.Id]) {
                linkedAddressIds.add(la.Id);
                addressIds.add(la.Linked_Address_From__r.Id);
                addressIds.add(la.Linked_Address_To__r.Id);
            }
            
            //loop to get addresses 9 levels deep...
            Integer listSize = addressIds.size();
            for (Integer i = 0; i < 9; i++) {
                System.debug('i: ' + i);
                
                for (Linked_Address__c la : [SELECT Id, Linked_Address_From__r.Id, Linked_Address_To__r.Id FROM Linked_Address__c WHERE Linked_Address_From__c IN :addressIds OR Linked_Address_To__c IN :addressIds]) {
                    linkedAddressIds.add(la.Id);
                    addressIds.add(la.Linked_Address_From__r.Id);
                    addressIds.add(la.Linked_Address_To__r.Id);
                }
                
                //if list didn't increase, means no more addresses to find so exit
                if (listSize == addressIds.size()) {
                    break;
                } else {
                    listSize = addressIds.size();
                }
            }
            
            system.debug('primaryAddress: ' + primaryAddress);
            
            for (Id childAddId : addressIds) {
                if (childAddId == primaryAddress.Id) {
                    continue;
                } else {
                    Address__c childAddress = new Address__c(Id = childAddId);
                    childAddress.Address_City__c = primaryAddress.Address_City__c;
                    childAddress.Address_Country__c = primaryAddress.Address_Country__c;
                    childAddress.Address_State__c = primaryAddress.Address_State__c;
                    childAddress.Address_Street__c = primaryAddress.Address_Street__c;
                    childAddress.Address_Zip_Code__c = primaryAddress.Address_Zip_Code__c;
                    childAddress.Cross_Streets__c = primaryAddress.Cross_Streets__c;
                    childAddress.Doorman__c = primaryAddress.Doorman__c;
                    childAddress.Facility_Manager__c = primaryAddress.Facility_Manager__c;
                    childAddress.Neighbourhood__c = primaryAddress.Neighbourhood__c;
                    childAddress.Notes__c = primaryAddress.Notes__c;
                    childAddress.Primary__c = primaryAddress.Primary__c;
                    childAddress.Type__c = primaryAddress.Type__c;
                    childAddress.Active__c = primaryAddress.Active__c;
                    childAddress.Inactive_Reason__c = primaryAddress.Inactive_Reason__c;
                    addressesToUpdate.add(childAddress); 
                }
            }
        }
        
        if (!addressesToUpdate.isEmpty()) {
            system.debug('addressesToUpdate: ' + addressesToUpdate);
            system.debug('addressesToUpdate.size(): ' + addressesToUpdate.size());
            update addressesToUpdate;
        }
    }
}