unpackaged/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Address_Country__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Country</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Address_Street__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Address_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Address_Zip_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Zip Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Cross_Streets__c.field-meta.xml
<CustomField>
    <fullName>Cross_Streets__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cross Streets</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Doorman__c.field-meta.xml
<CustomField>
    <fullName>Doorman__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Doorman</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Facility_Manager__c.field-meta.xml
<CustomField>
    <fullName>Facility_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses (Facility Manager)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Neighbourhood__c.field-meta.xml
<CustomField>
    <fullName>Neighbourhood__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Neighbourhood</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Vacation Home</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
                <isActive>false</isActive>
                <label>Cottage</label>
            </value>
            <value>
                <fullName>Family Home</fullName>
                <isActive>false</isActive>
                <label>Family Home</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/Linked_Address__c.object-meta.xml
<CustomObject>
    <label>Linked Address</label>
    <nameField>
        <displayFormat>LA-{0}</displayFormat>
        <label>Linked Addresse #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Address__c/fields/Link_Address_To__c.field-meta.xml
<CustomField>
    <fullName>Link_Address_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is just used to initially do the cloning</description>
    <label>Link Address To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Linked Addresses</relationshipLabel>
    <relationshipName>Linked_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address__c</fullName>
    <formula>HYPERLINK('/' + Linked_Address_From__c, Linked_Address_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Address_To__c, Linked_Address_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_From__c</fullName>
    <label>Linked Address From</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses (From)</relationshipLabel>
    <relationshipName>Linked_Addresses_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This address will initially be synced to the address selected here. Then they will be synced up whenever either address is updated.</inlineHelpText>
    <label>Linked Address To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Address_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses</relationshipLabel>
    <relationshipName>Linked_Addresses_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TriggerHandlerLinkedAddress.cls
public  class TriggerHandlerLinkedAddress extends TriggerHandler {
    
    // Constructor 
    public TriggerHandlerLinkedAddress() {}
    
    /* Trigger context overrides */
    public override void beforeInsert() {
        if(RecursiveTriggerHandler.runOnce()){
            beforeLogic(Trigger.new);
        }
    }
    public override void beforeUpdate() {}
    public override void beforeDelete() {}
    public override void afterInsert() {}
    public override void afterUpdate() {}
    public override void afterDelete() {}
    public override void afterUndelete() {}
    
    private void beforeLogic(List<sObject> newLinkedAddresses){
        system.debug('beforeLogic');
        List<Linked_Address__c> newLinkedAddressList = (List<Linked_Address__c>) newLinkedAddresses;
        List<Address__c> addressesToCreate = new List<Address__c>();
       
        for(Linked_Address__c linkedAdd : newLinkedAddressList){
            system.debug('linkedAdd1: ' + linkedAdd);
            
            //Create new address logic
            if (linkedAdd.Link_Address_To__c != NULL) {
                for (Address__c fromAdd : [SELECT Address_City__c,Address_Country__c,Address_State__c,Address_Street__c,Address_Zip_Code__c,Cross_Streets__c,Doorman__c,Facility_Manager__c,Id,Neighbourhood__c,Notes__c,Primary__c,Type__c,Inactive_Reason__c 
                                           FROM Address__c 
                                           WHERE Id = :linkedAdd.Linked_Address_From__c LIMIT 1]) {
                                               Address__c newAdd = new Address__c();
                                               newAdd.Contact_Name__c = linkedAdd.Link_Address_To__c;
                                               newAdd.Address_City__c = fromAdd.Address_City__c;
                                               newAdd.Address_Country__c = fromAdd.Address_Country__c;
                                               newAdd.Address_State__c = fromAdd.Address_State__c;
                                               newAdd.Address_Street__c = fromAdd.Address_Street__c;
                                               newAdd.Address_Zip_Code__c = fromAdd.Address_Zip_Code__c;
                                               newAdd.Cross_Streets__c = fromAdd.Cross_Streets__c;
                                               newAdd.Doorman__c = fromAdd.Doorman__c;
                                               newAdd.Facility_Manager__c = fromAdd.Facility_Manager__c;
                                               newAdd.Neighbourhood__c = fromAdd.Neighbourhood__c;
                                               newAdd.Notes__c = fromAdd.Notes__c;
                                               newAdd.Primary__c = fromAdd.Primary__c;
                                               newAdd.Type__c = fromAdd.Type__c;
                                               insert newAdd; 
                                               system.debug('newAdd: ' + newAdd);
                                               linkedAdd.Linked_Address_To__c = newAdd.Id;
                                               system.debug('newAdd2: ' + newAdd);
                                           }
            } else if (linkedAdd.Linked_Address_To__c != NULL) { //link to existing address logic so sync
                for (Address__c fromAdd : [SELECT Address_City__c,Address_Country__c,Address_State__c,Address_Street__c,Address_Zip_Code__c,Cross_Streets__c,Doorman__c,Facility_Manager__c,Id,Neighbourhood__c,Notes__c,Primary__c,Type__c,Inactive_Reason__c
                                           FROM Address__c 
                                           WHERE Id = :linkedAdd.Linked_Address_From__c LIMIT 1]) {
                                               Address__c syncAdd = new Address__c(Id = linkedAdd.Linked_Address_To__c);
                                               syncAdd.Address_City__c = fromAdd.Address_City__c;
                                               syncAdd.Address_Country__c = fromAdd.Address_Country__c;
                                               syncAdd.Address_State__c = fromAdd.Address_State__c;
                                               syncAdd.Address_Street__c = fromAdd.Address_Street__c;
                                               syncAdd.Address_Zip_Code__c = fromAdd.Address_Zip_Code__c;
                                               syncAdd.Cross_Streets__c = fromAdd.Cross_Streets__c;
                                               syncAdd.Doorman__c = fromAdd.Doorman__c;
                                               syncAdd.Facility_Manager__c = fromAdd.Facility_Manager__c;
                                               syncAdd.Neighbourhood__c = fromAdd.Neighbourhood__c;
                                               syncAdd.Notes__c = fromAdd.Notes__c;
                                               syncAdd.Primary__c = fromAdd.Primary__c;
                                               syncAdd.Type__c = fromAdd.Type__c;
                                               syncAdd.Inactive_Reason__c = fromAdd.Inactive_Reason__c;
                                               RecursiveTriggerHandler.isFirstTime = TRUE;
                                               update syncAdd; 
                                               system.debug('syncAdd: ' + syncAdd);
                                           }
            }
        }
    }
}