unpackaged/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Address__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/Linked_Address__c.object-meta.xml
<CustomObject>
    <label>Linked Address</label>
    <nameField>
        <displayFormat>LA-{0}</displayFormat>
        <label>Linked Addresse #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address__c</fullName>
    <formula>HYPERLINK('/' + Linked_Address_From__c, Linked_Address_From__r.Name) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Address_To__c, Linked_Address_To__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_From__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_From__c</fullName>
    <label>Linked Address From</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses (From)</relationshipLabel>
    <relationshipName>Linked_Addresses_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Address_To__c.field-meta.xml
<CustomField>
    <fullName>Linked_Address_To__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <inlineHelpText>This address will initially be synced to the address selected here. Then they will be synced up whenever either address is updated.</inlineHelpText>
    <label>Linked Address To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Linked_Address_From__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Linked Addresses</relationshipLabel>
    <relationshipName>Linked_Addresses_To</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Linked_Address__c/fields/Linked_Between__c.field-meta.xml
<CustomField>
    <fullName>Linked_Between__c</fullName>
    <formula>HYPERLINK('/' + Linked_Address_From__r.Contact_Name__c, Linked_Address_From__r.Contact_Name__r.Full_Name__c) &amp; ' &lt;-&gt; ' &amp; HYPERLINK('/' + Linked_Address_To__r.Contact_Name__c, Linked_Address_To__r.Contact_Name__r.Full_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Between</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/LinkedAddressController.cls
public class LinkedAddressController {
    @AuraEnabled
    public static List <LinkedAddressWrapper> getLinkedAddresses(Id addressId) {
        system.debug('LinkedAddressController');
        List <LinkedAddressWrapper> linkedAddresses = new List<LinkedAddressWrapper>();
        
        Set<Id> linkedAddressIds = new Set<Id>();
        Set<Id> addressIds = new Set<Id>();
        Set<Id> alreadyLinkedIds = new Set<Id>();

        for (Linked_Address__c la : [SELECT Id,Name,Linked_Between__c,Linked_Address_To__c,Linked_Address_From__c,Linked_Address_From__r.Id,Linked_Address_From__r.Name,Linked_Address_From__r.Contact_Name__c,Linked_Address_To__r.Id,Linked_Address_To__r.Name,Linked_Address_To__r.Contact_Name__c
                                     FROM Linked_Address__c
                                     WHERE Linked_Address_From__c = :addressId OR Linked_Address_To__c = :addressId]) {
                                         linkedAddressIds.add(la.Id);
                                         if (la.Linked_Address_From__c != addressId) {
                                             linkedAddresses.add(new LinkedAddressWrapper(la, la.Linked_Address_From__r.Name, la.Linked_Address_From__r.Id,la.Linked_Address_From__r.Contact_Name__c, '1 - DIRECT'));
                                             alreadyLinkedIds.add(la.Linked_Address_From__r.Id);
                                         } else {
                                             linkedAddresses.add(new LinkedAddressWrapper(la, la.Linked_Address_To__r.Name, la.Linked_Address_To__r.Id,la.Linked_Address_To__r.Contact_Name__c,'1 - DIRECT'));
                                             alreadyLinkedIds.add(la.Linked_Address_To__r.Id);
                                         }
                                         addressIds.add(la.Linked_Address_From__r.Id);
                                         addressIds.add(la.Linked_Address_To__r.Id);
        }
        
        //loop 5 times to get addresses 9 levels deep...
        Integer listSize = addressIds.size();
        for (Integer i = 2; i < 11; i++) {
            System.debug('i: ' + i);
            
            for (Linked_Address__c la : [SELECT Id,Name,Linked_Between__c,Linked_Address_To__c,Linked_Address_From__c,Linked_Address_From__r.Id,Linked_Address_From__r.Name,Linked_Address_From__r.Contact_Name__c,Linked_Address_To__r.Id,Linked_Address_To__r.Name,Linked_Address_To__r.Contact_Name__c
                                         FROM Linked_Address__c
                                         WHERE (Linked_Address_From__c IN :addressIds OR Linked_Address_To__c IN :addressIds) AND Id NOT IN :linkedAddressIds]) {
                                             if (!alreadyLinkedIds.contains(la.Linked_Address_From__r.Id)) {
                                                 linkedAddresses.add(new LinkedAddressWrapper(la, la.Linked_Address_From__r.Name, la.Linked_Address_From__r.Id,la.Linked_Address_From__r.Contact_Name__c, String.valueOf(i) + ' - NON-DIRECT'));
                                             }
                                             if (!alreadyLinkedIds.contains(la.Linked_Address_To__r.Id)) {
                                                 linkedAddresses.add(new LinkedAddressWrapper(la, la.Linked_Address_To__r.Name, la.Linked_Address_To__r.Id,la.Linked_Address_To__r.Contact_Name__c,String.valueOf(i) + ' - NON-DIRECT'));
                                             }
                                             alreadyLinkedIds.add(la.Linked_Address_From__r.Id);
                                             alreadyLinkedIds.add(la.Linked_Address_To__r.Id);
                                             addressIds.add(la.Linked_Address_From__r.Id);
                                             addressIds.add(la.Linked_Address_To__r.Id);
                                         }
            
            //if list didn't increase, means no more linked to find so exit
            if (listSize == addressIds.size()) {
                break;
            } else {
                listSize = addressIds.size();
            }
        }
        /***/
        
        
        
        
        /*for (Linked_Address__c fromAdd : [SELECT Id,Name,Linked_Address_To__c,Linked_Address_From__c,Linked_Address_From__r.Id,Linked_Address_From__r.Name,Linked_Address_From__r.Contact_Name__c
                                          FROM Linked_Address__c
                                          WHERE Linked_Address_To__c = :addressId AND Linked_Address_From__c != :addressId]) {
                                              system.debug('fromAdd: ' + fromAdd);
                                              linkedAddresses.add(new LinkedAddressWrapper(fromAdd, fromAdd.Linked_Address_From__r.Name, fromAdd.Linked_Address_From__r.Id,fromAdd.Linked_Address_From__r.Contact_Name__c));
                                          }
        
        for (Linked_Address__c toAdd : [SELECT Id,Name,Linked_Address_From__c,Linked_Address_To__c,Linked_Address_To__r.Id,Linked_Address_To__r.Name,Linked_Address_To__r.Contact_Name__c
                                        FROM Linked_Address__c
                                        WHERE Linked_Address_From__c = :addressId AND Linked_Address_To__c != :addressId]) {
                                            system.debug('toAdd: ' + toAdd);
                                            linkedAddresses.add(new LinkedAddressWrapper(toAdd, toAdd.Linked_Address_To__r.Name, toAdd.Linked_Address_To__r.Id,toAdd.Linked_Address_To__r.Contact_Name__c));
                                        }
        system.debug('linkedAddresses: ' + linkedAddresses);*/

        return linkedAddresses;
    }
    
    public class LinkedAddressWrapper {
        @AuraEnabled
        public Linked_Address__c rec {get; set;}
        @AuraEnabled
        public String address {get; set;}
        @AuraEnabled
        public Id addressId {get; set;}
        @AuraEnabled
        public Id contactId {get; set;}
        @AuraEnabled
        public String syncLevel {get;set;}
        @AuraEnabled
        public Integer linkBetween {get;set;}
        
        public LinkedAddressWrapper(Linked_Address__c rec, String address, Id addressId, Id contactId, String syncLevel) {     
            this.rec = rec;
            this.address = address;
            this.addressId = addressId;
            this.contactId = contactId;
            this.syncLevel = syncLevel;
        }
    }
}