unpackaged/main/default/objects/Insider_Team__c/Insider_Team__c.object-meta.xml
<CustomObject>
    <label>Insider Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Insider Team  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insider Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <displayFormat>IT{000}</displayFormat>
    <label>Insider Team #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team_Member__c/Insider_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Insider Team Member</label>
    <nameField>
        <displayFormat>ITM-{0}</displayFormat>
        <label>Insider Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insider Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Insider_Team_Member__c/fields/Insider_Team__c.field-meta.xml
<CustomField>
    <fullName>Insider_Team__c</fullName>
    <label>Insider Team</label>
    <referenceTo>Insider_Team__c</referenceTo>
    <relationshipLabel>Insider Team Members</relationshipLabel>
    <relationshipName>Insider_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Insider_Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Insider_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/InsiderTeamTest.cls
@isTest
private class InsiderTeamTest { 
        
    @isTest 
    static void testTriggers() {
        Test.StartTest();
        Insider_Team__c itA = new Insider_Team__c(Name = 'Team A', Active__c = TRUE);
        Insider_Team__c itB = new Insider_Team__c(Name = 'Team B', Active__c = FALSE);
        INSERT itA;
        INSERT itB;
        
        User[] usrList = [Select Id FROM User WHERE IsActive = True AND User.Profile.UserLicense.Name = 'Salesforce' LIMIT 2];
        Insider_Team_Member__c itmA = new Insider_Team_Member__c(Insider_Team__c = itA.Id, Team_Member__c = usrList[0].Id);
        Insider_Team_Member__c itmB = new Insider_Team_Member__c(Insider_Team__c = itB.Id, Team_Member__c = usrList[1].Id);
        Insider_Team_Member__c itmC = new Insider_Team_Member__c(Insider_Team__c = itA.Id, Team_Member__c = usrList[1].Id);
        Insider_Team_Member__c itmD = new Insider_Team_Member__c(Insider_Team__c = itB.Id, Team_Member__c = usrList[0].Id);
        INSERT itmA;
        INSERT itmB;
        INSERT itmC;
        INSERT itmD;
        
        DELETE itmA;
        UNDELETE itmA;

        DELETE itA;
        UNDELETE itA;
        
        itB.Active__c = TRUE;
        UPDATE itB;
        Test.StopTest();
    }
}