unpackaged/main/default/objects/Flight_Booking__c/Flight_Booking__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Flight #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Flight_Booking__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot find airline.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Account - Generic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Arrival Airport</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Arrival_City__c.field-meta.xml
<CustomField>
    <fullName>Arrival_City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Arrival City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/ArrivalDateforEmail__c.field-meta.xml
<CustomField>
    <fullName>ArrivalDateforEmail__c</fullName>
    <formula>IF( Arrival_DST__c = true,  Arrival_Date__c - (4/24), Arrival_Date__c - (5/24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ArrivalDateforEmail</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Departure Airport</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Departure_City__c.field-meta.xml
<CustomField>
    <fullName>Departure_City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Departure City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/DepartureTimeForEmail__c.field-meta.xml
<CustomField>
    <fullName>DepartureTimeForEmail__c</fullName>
    <formula>IF( Departure_DST__c = true,  Departure_Date__c - (4/24), Departure_Date__c - (5/24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DepartureTimeForEmail</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Flight_Booking__c/fields/Logbook__c.field-meta.xml
<CustomField>
    <fullName>Logbook__c</fullName>
    <label>Logbook</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flight_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/FlightRecordsSortingController.cls
/* 
    * Class Name : FlightRecordsSortingController
    * Description : Class for FlightRecordsSortingController.
    * Created Date : 17/01/2024
*/
public class FlightRecordsSortingController {
    public static String recordId {get; set;}
    public List<Flight_Booking__c> relatedFlightRecords {get{
        
        return relatedFlightRecords = [SELECT Id,Airline__r.Name,Departure_City__c,Departure_Airport__c,Departure_Date__c,DepartureTimeForEmail__c,Arrival_City__c,Arrival_Airport__c,Arrival_Date__c,ArrivalDateforEmail__c
        FROM Flight_Booking__c
        WHERE Logbook__c =: recordId  Order by Departure_Date__c,DepartureTimeForEmail__c];
    } private set;}
}